v01/http.go, v01/http_test.go
Currently the Header processing in UnmarshalBinary makes use of `TrimLeft` which will have undesirable effects when a character in the cutset immediately follows the hyphen.  For example a header value of `CE-CloudEventsVersion` would be converted to `loudEventsVersion`.
This change amends TestHTTPMarshallerFromRequestBinaryBase64Success to add a header to exercise the identified issue and also changes TrimLeft to TrimPrefix within http.go.
Signed-off-by: Richard Gee <richard@technologee.co.uk>
=> Make use of TrimPrefix for binary headers

README.md, event.go, v02/converter.go, v02/converter_test.go, v02/event.go, v02/event_test.go, v02/http.go, v02/http_test.go
This change updates the Go SDK to support spec version 0.2. This includes updating property names to drop the redundant 'event' prefix and updates the cloudeventsversion property to specversion. The binaryUnmarshal method now uses the cloudevents structtag to determine the header name for each well known property. This change also includes helper methods on the generic Event interface that handle type conversion. This change also updates the 0.1 support to use lowercase property names.
=> update sdk to support spec version 0.2

cmd/samples/complex/sender/main.go, pkg/cloudevents/client/client.go, pkg/cloudevents/client/defaulters.go, pkg/cloudevents/client/defaulters_test.go, pkg/cloudevents/client/options.go, pkg/cloudevents/client/options_test.go
fixes: https://github.com/cloudevents/sdk-go/issues/22
Attempting to reduce friction for the producer of events when using the client.
At the moment we need to do something like this to make a event context:
```go
func (d *Demo) context() cloudevents.EventContext {
now := time.Now()
ctx := cloudevents.EventContextV01{
EventID:     uuid.New().String(),
EventType:   d.EventType,
EventTime:   &types.Timestamp{Time: now},
Source:      types.URLRef{URL: d.Source},
ContentType: &d.ContentType,
}.AsV01()
return ctx
}
```
But with this change, we can add new client options to enable defaulting:
```go
c, err := client.NewHTTPClient(
client.WithTarget(env.HTTPTarget),
client.WithHTTPEncoding(encoding),
client.WithUUIDs(),
client.WithTimeNow(),
)
```
And now the producer of the event has less to …
=> Adding Client Option for default ID and Time when using client.Send()

cmd/samples/http/receiver/main.go, pkg/cloudevents/client/client_http.go, pkg/cloudevents/client/options.go, pkg/cloudevents/client/options_test.go, pkg/cloudevents/transport/http/transport.go
Integrating with https://github.com/mchmarny/knative-ws-example I found that in this example it was impossible to use the sdk because the sdk did not let me choose which path the handler should use.
Moved the http internals to use a handler and add the ability to set that handler to something else.
=> Adding the option to set the handle path for http client.

pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v01_test.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v02_test.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/codec_v03_test.go
Check the header name's length before slicing it.
Without this, I was getting problems when sending an `http.Request`'s headers to `Decode`. In particular the `Host` header using `CodecV01` in binary mode.
=> Check the header name's length before slicing it

README.md
Now that automation is turned on for the repo we can show a status badge in the README.
Signed-off-by: Mark Peek <markpeek@vmware.com>
=> Add circleci badge to README

README.md, cmd/samples/complex/httptonats/main.go, cmd/samples/http/receiver/main.go, cmd/samples/http/sender/main.go, cmd/samples/http/sleepy/main.go, cmd/samples/nats/receiver/main.go, pkg/cloudevents/client/client.go, pkg/cloudevents/client/client_http.go, pkg/cloudevents/client/client_nats.go, pkg/cloudevents/client/client_test.go, pkg/cloudevents/client/options.go, pkg/cloudevents/client/options_test.go, pkg/cloudevents/context/context.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/nats/transport.go, pkg/cloudevents/transport/transport.go
* StartReceiver now returns a context. This is intended to be an fyi for the caller of the client. to extract data around how the transport was setup. If the client knows it is using an http transport, then it can fetch out the port or path that is being used and advertise it. This is demoed in the unit test for client.
* client.WithPort can now accept 0 as a valid port and the transport will pick a valid open port for you.
* The `transport.Sender` interface was modified to support Stop: `StartReceiver(context.Context) (context.Context, error)` and `StopReceiver(context.Context) error` are added. The logic on starting and stopping a transport is now inside the transport and removed from the client object code.
Fixes https://github.com/cloudevents/sdk-go/issues/43, …
=> Add client.StopReceiver

pkg/cloudevents/client/defaulters_test.go, pkg/cloudevents/context/context.go, pkg/cloudevents/context/context_test.go, pkg/cloudevents/datacodec/xml/data.go, pkg/cloudevents/datacodec/xml/data_test.go, pkg/cloudevents/event_response.go, pkg/cloudevents/event_response_test.go, pkg/cloudevents/eventcontext_v01_test.go, pkg/cloudevents/eventcontext_v02_test.go, pkg/cloudevents/eventcontext_v03_test.go, pkg/cloudevents/types/allocate_test.go, pkg/cloudevents/types/timestamp.go, pkg/cloudevents/types/timestamp_test.go, pkg/cloudevents/types/urlref.go, pkg/cloudevents/types/urlref_test.go
This brings unit test coverage to `80.4%`
Fixes: https://github.com/cloudevents/sdk-go/issues/35
=> Adding unit tests where tests are lacking.

cmd/samples/http/sender/main.go, cmd/samples/simple/http/receiver/main.go, pkg/cloudevents/client/client_test.go, pkg/cloudevents/event.go, pkg/cloudevents/event_test.go, pkg/cloudevents/transport/http/context.go, pkg/cloudevents/transport/http/options.go, pkg/cloudevents/transport/http/options_test.go, pkg/cloudevents/transport/http/transport.go
This change adds the option for `httptransport.WithHeader(key, value)`. This will add a header to the outbound http request for custom http headers. 
Also added full pretty printing to help debug this for event and http TransportContext.
Supersedes https://github.com/cloudevents/sdk-go/pull/73
Thanks @matzew for pointing out the `req.Close` option, and for testing the client out!!
=> Pass headers from transport request setup to out-bound request.

cmd/samples/simple/http/receiver/main.go, cmd/samples/simple/http/sender/main.go, pkg/cloudevents/transport/http/context.go, pkg/cloudevents/transport/http/context_test.go, pkg/cloudevents/transport/http/transport.go
=> Adding header plumbing to the http transport.

pkg/cloudevents/client/client.go, pkg/cloudevents/client/defaulters.go, pkg/cloudevents/client/observability.go, pkg/cloudevents/codec/jsoncodec.go, pkg/cloudevents/codec/observability.go, pkg/cloudevents/datacodec/codec.go, pkg/cloudevents/datacodec/json/data.go, pkg/cloudevents/datacodec/json/observability.go, pkg/cloudevents/datacodec/observability.go, pkg/cloudevents/datacodec/xml/data.go, pkg/cloudevents/datacodec/xml/observability.go, pkg/cloudevents/event.go, pkg/cloudevents/event_response.go, pkg/cloudevents/eventcontext.go, pkg/cloudevents/eventcontext_v01.go, pkg/cloudevents/eventcontext_v02.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/transport/http/codec.go, pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/message.go, pkg/cloudevents/transport/http/observability.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/transport.go
Second pass adding godocs to exported methods and variables. Un-exporting metrics helpers.
Fixes https://github.com/cloudevents/sdk-go/issues/70
Fixes https://github.com/cloudevents/sdk-go/issues/49
=> Adding more documentation to the implementation.

pkg/cloudevents/event.go, pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext.go, pkg/cloudevents/eventcontext_v01.go, pkg/cloudevents/eventcontext_v02.go, pkg/cloudevents/eventcontext_v03.go
**Proposed Changes**
* Adding an ExtensionAs(string, interface{}) function as part of EventContext interface to easily read extension attributes. Only supports decoding string extensions. Might need to use something like DataAs decoding functionality to avoid duplicating code, and better support multiple extension types.
* Adding a SetExtension(string, interface{}) function to every EventContextV* struct. As it mutates the underlying map, we need a pointer receiver, thus I couldn't add it as part of the EventContext interface.
=> Adding ExtensionAs and SetExtension methods

pkg/cloudevents/client/observability.go, pkg/cloudevents/codec/observability.go, pkg/cloudevents/datacodec/json/observability.go, pkg/cloudevents/datacodec/observability.go, pkg/cloudevents/datacodec/xml/observability.go, pkg/cloudevents/transport/http/observability.go
[Standard practice](https://godoc.org/go.opencensus.io/plugin/ocgrpc) for OpenCensus measure names is to qualify them with project names so the names are unique. Since measure names are never exported (only view names), this is a safe change.
Also the measures are now exported so library users can create custom views with them This is also standard practice.
/cc @n3wscott
=> Qualify stat names to avoid collisions

pkg/cloudevents/transport/http/context.go, pkg/cloudevents/transport/http/transport.go
I was passing headers by ref, not by value and header values were getting duplicated.
=> found a bug in how header comes from context, fixed.

alias.go, cmd/samples/http/receiver/main.go, cmd/samples/http/responder/main.go, cmd/samples/http/sender/main.go, cmd/samples/http/sleepy/main.go, cmd/samples/simple/http/receiver/main.go, cmd/samples/simple/http/sender/main.go
Lets us go from:
```go
"github.com/cloudevents/sdk-go/pkg/cloudevents"
"github.com/cloudevents/sdk-go/pkg/cloudevents/client"
cloudeventshttp "github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http"
```
to 
```go
"github.com/cloudevents/sdk-go"
```
=> Adding alias to top level to make http integrations import less.

alias.go, pkg/cloudevents/codec/jsoncodec.go, pkg/cloudevents/data_content_encoding.go, pkg/cloudevents/data_content_encoding_test.go, pkg/cloudevents/event.go, pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext.go, pkg/cloudevents/eventcontext_v01.go, pkg/cloudevents/eventcontext_v02.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/eventcontext_v03_test.go, pkg/cloudevents/extensions.go, pkg/cloudevents/transport/http/codec_v03.go, test/http/loopback_v03_test.go
Fixes https://github.com/cloudevents/sdk-go/issues/101
Adding support to v0.3 to send and receive base64 payloads.
=> Adding Data Content Encoding support.

pkg/cloudevents/transport/http/transport.go
In a lot of places, `transport.go` prints the full body of the response. This seems ripe with the possibility for the wrong data to end up in the wrong log stream / log drain 👎
This removes many of them. Thanks!
=> Stop spewing request data into log stream

go.mod, go.sum, pkg/cloudevents/codec/jsoncodec.go, pkg/cloudevents/context/logger.go, pkg/cloudevents/context/logger_test.go, pkg/cloudevents/event.go, pkg/cloudevents/event_reader.go, pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext.go, pkg/cloudevents/eventcontext_v01_reader.go, pkg/cloudevents/eventcontext_v01_test.go, pkg/cloudevents/eventcontext_v02_reader.go, pkg/cloudevents/eventcontext_v02_test.go, pkg/cloudevents/eventcontext_v03_reader.go, pkg/cloudevents/eventcontext_v03_test.go, pkg/cloudevents/transport/http/codec.go, pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/nats/transport.go
As a follow-up to https://github.com/cloudevents/sdk-go/pull/107, this moves the SDK to use Zap for logging and cleans up some more logging messages that, while useful for debugging, are not wanted in production. 😺
=> Use Zap Logging

go.mod, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go
This adds a test to verify we aren't opening and closing HTTP
connections too often when sending events to a single host. The test
will fail in CI (it fails locally) until I push a subsequent change to
actually fix this issue.
The test tracks the count of opened HTTP connections and fails if it's
an amount more than double the expected concurrency. In practice, when
this is fixed properly, the number of opened connections should be
close to if not exactly the expected concurrency. In the case of this
test, that would be 200 new connections. As the code stands today,
when I run this on my laptop, we actually opening over 3000 new
connections in just the 1 second this test runs.
Related to #98
=> Don't open and close HTTP connections too often

alias.go, docs/README.md, pkg/cloudevents/client/client.go, pkg/cloudevents/codec/jsoncodec.go, pkg/cloudevents/content_type.go, pkg/cloudevents/datacodec/codec.go, pkg/cloudevents/event.go, pkg/cloudevents/event_data.go, pkg/cloudevents/event_data_test.go, pkg/cloudevents/event_interface.go, pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/transport/http/codec_test.go, pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v01_test.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v02_test.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/codec_v03_test.go, pkg/cloudevents/transport/nats/codec_test.go, pkg/cloudevents/transport/nats/codec_v02_test.go, pkg/cloudevents/transport/nats/codec_v03_test.go, test/http/loopback_setters_test.go, test/http/validation.go
There was an issue developing where the data payload was un-trustable to the codecs. I needed a way to set the data and have it pass through the event data encoding, which is not the same as the transport encoding. So now there is a new method on event:
```go
event.SetData(mydata)
```
And this results in the event data becoming encoded on the event according to the event's encoding settings.
=> Encoding cleanup, adding event.DataEncoded flag, adding event.SetData

pkg/cloudevents/transport/http/transport_test.go
I am getting errors with the new transport test if it is run on my mac:
```
transport_test.go:122: error sending concurrent CloudEvents: unexpected error sending CloudEvent Post http://[::]:64451: read tcp [::1]:64485->[::1]:64451: read: connection reset by peer
```
I found that lowering the concurrency limit to `100` allows the test to pass ~50% of the time and `64` 100% of the time. 
used `-test.count = 100` to figure this out.
=> Fixing error getting locally with new test.

pkg/cloudevents/event_reader.go
This function swallows a parsing error, and that seems worth documenting.
/cc @n3wscott
=> Document GetDataMediaType

alias.go, pkg/cloudevents/transport/http/options.go, pkg/cloudevents/transport/http/options_test.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go
Add HTTP middleware as an option.
I am planning to use this to add OpenCensus zipkin tracing:
```golang
httpTransport, err := cloudevents.NewHTTPTransport(cloudevents.WithBinaryEncoding(), cloudevents.WithMiddleware(tracing.HTTPSpanMiddleware))
```
=> HTTP Middleware

pkg/cloudevents/transport/amqp/codec.go, pkg/cloudevents/transport/amqp/codec_test.go
An extension attribute with value `nil` is now ignored.
=> Fix crash with nil value in binary AMQP message

alias.go, cmd/samples/http/converter/receiver/main.go, cmd/samples/http/converter/sender/main.go, pkg/cloudevents/client/client.go, pkg/cloudevents/client/options.go, pkg/cloudevents/client/receiver.go, pkg/cloudevents/transport/amqp/codec.go, pkg/cloudevents/transport/amqp/codec_v02.go, pkg/cloudevents/transport/amqp/codec_v02_test.go, pkg/cloudevents/transport/amqp/codec_v03.go, pkg/cloudevents/transport/amqp/codec_v03_test.go, pkg/cloudevents/transport/amqp/transport.go, pkg/cloudevents/transport/codec.go, pkg/cloudevents/transport/http/codec.go, pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/nats/codec.go, pkg/cloudevents/transport/nats/codec_v02.go, pkg/cloudevents/transport/nats/codec_v03.go, pkg/cloudevents/transport/nats/transport.go, pkg/cloudevents/transport/transport.go, test/http/conversion.go, test/http/conversion_v02_test.go
There are cases when receiving cloudevents that the incoming message needs to be normalized into a cloudevents format to be consumed by downstream functions. This PR adds the ability to add a conversion function for unconvertible transport messages.
See the conversion test or the new sample code for an example.
=> Adding Conversion hook.

go.mod, pkg/cloudevents/transport/http/codec_test.go, pkg/cloudevents/transport/http/message.go, pkg/cloudevents/transport/http/message_test.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go
For issue #140 
Related changes/fixes:
Re-use Message as part of Response so a response can also be treated
as a Message.
Added/used copyHeadersEnsure() to ensure headers are not dropped on the
floor if copied into a nil Header map in a zero-initialized
http.Request or Message.
=> Issue #140: Add Message.ToRequest()/FromRequest

pkg/cloudevents/transport/http/encoding.go, pkg/cloudevents/transport/http/options.go, pkg/cloudevents/transport/http/options_test.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go
Fix for #131 
GetPort() calls net.Listen() on demand so it will always return the
actual listening port if port 0 was requested.
WithListener() allows the user to provide their own net.Listener, allows:
- alternate networks (e.g. "tcp4" or "tcp6" to restrict IP versions)
- listening interface to be specified for multi-homed hosts
- non-TCP listeners - GetPort() won't work but everything else will.
Also fixed a cancellation race in StartReceiver that showed up in tests.
=> Add WithListener to http transport, ensure GetPort() always returns active port.

cmd/samples/amqp/receiver/main.go, cmd/samples/complex/sender/main.go, cmd/samples/http/sleepy/main.go, pkg/cloudevents/client/client_test.go, pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext_v01.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/observability/observer.go, pkg/cloudevents/transport/http/message_test.go, pkg/cloudevents/transport/http/options_test.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go, pkg/cloudevents/transport/nats/codec_test.go, pkg/cloudevents/transport/nats/transport.go, pkg/cloudevents/types/urlref.go, test/http/loopback.go, test/http/tap_handler.go, test/http/validation.go
golangcli-lint combines multiple linters, including go vet. It has
good default settings - not much noise, I recommend it. Fixes are to:
- Remove dead/unreachable code
- Fix missing error checks:
I mostly marked them intentional with `_ = foo()`, I think this is right
One was in in a `defer` statement I fixed by returning it.
- Minor simplifications (from 'gosimple' linter)
=> Fix issues found by  golangci-lint

go.sum
Seeing weird behavior where every `go build` was adding a line for
package github.com/gogo/protobuf to go.mod. `go tidy` would remove it
as unused, but the next `go build` would put it back.
I removed all the github.com/gogo/protobuf lines from go.sum and ran
`go tidy`. It put all but one of the lines back. Now everything works.
Weird.
=> Remove bogus entry from go.sum

pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go
If a HTTP request does not contain the `ce-specversion` header then the
process of converting the request to an event returns a `nil`
event and a non-fatal error value. Unfortunately, in this situation,
the code continued to process the request resulting in an attempt to
de-reference the `nil` event value.
Fix by adding an additional condition to the error handling. Now
conversions that yield a non-fatal error must also return a non-nil
event, otherwise a HTTP 400 (Bad Request) status is returned.
=> Fix segfault if ce-specversion header missing

pkg/cloudevents/event_marshal_test.go, pkg/cloudevents/transport/amqp/codec_test.go, pkg/cloudevents/transport/http/codec_test.go, pkg/cloudevents/transport/http/message.go, pkg/cloudevents/transport/nats/codec_test.go, test/http/loopback.go
Various minor syntactic changes, no change in behavior.
Removed TestUnmarshal_nilEvent(t *testing.T)
Calling json.Unmarshal with a nil argument is always an error as
per the json package doc. `go vet` even reports it statically.
There is no need to verify that here, it's not special to cloudevents.
=> Changes to keep `go vet` happy.

alias.go, cmd/samples/stats/main.go, pkg/cloudevents/observability/observer.go
For applications that want to use tracing to do network level traces and not profile traces, the sdk pushes too much data. 
Fixes #168 
cc: @Harwayne
=> Add a method to disable tracing.

pkg/cloudevents/transport/doc.go, pkg/cloudevents/transport/x/doc.go, pkg/cloudevents/transport/x/example_implementing_test.go, pkg/cloudevents/transport/x/example_using_test.go, pkg/cloudevents/transport/x/message.go
See Issu "Message interface for inter-transport use." #162
This PR is not intended to be pushed, it illustrates some ideas directly as working code and examples. As we agree on if/how the ideas  should be integrated, I'll submit PRs to merge them into the main transport package.
It is a little easier to read as godoc, for convenience I put it here https://alanconway.github.io/godoc/pkg/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/x/index.html
or you can use godoc to generate it locally
=> Code and examples for proposed changes/additions to transport APIs

pkg/cloudevents/transport/http/transport.go
=> fix extra header write.

go.mod, pkg/cloudevents/transport/pubsub/transport.go
Found a blocking issue on pubsub transport if a subscriber had an error. The subscriber would never be able to signal up to the parent that it was ready because the Receive method would block until the parent context was finished.
Fixed.
=> Propagate pubsub subscriber errors

pkg/cloudevents/transport/amqp/codec.go, pkg/cloudevents/transport/pubsub/codec.go
@nachocano found a npe in his logs. I think this will fix.
=> Parse timestamp can return nil. Check for nil.

alias.go, pkg/cloudevents/transport/http/codec.go, pkg/cloudevents/transport/http/codec_structured.go, pkg/cloudevents/transport/http/codec_test.go, pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v01_test.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v02_test.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/codec_v03_test.go, pkg/cloudevents/transport/http/codec_v1.go, pkg/cloudevents/transport/http/codec_v1_test.go, pkg/cloudevents/transport/http/encoding.go, test/http/loopback.go, test/http/loopback_v01_test.go, test/http/loopback_v1_test.go
This adds end to end tests for 1.0, but also comments out the 1.0 base64 test because we need to rework how data is compared as a follow-up.
This fixes a race condition in the http codecs on load-up.
Fixes: https://github.com/cloudevents/sdk-go/issues/193
=> Adding end to end tests and fixing codec for races.

pkg/cloudevents/event.go, pkg/cloudevents/event_marshal.go, pkg/cloudevents/transport/http/codec_v1_test.go
Related to https://github.com/cloudevents/sdk-go/issues/195
Leverage the native base64 encoding that the golang json lib uses.
=> use []byte and not string for base64 json key.

pkg/cloudevents/transport/http/options.go, pkg/cloudevents/transport/http/options_test.go, pkg/cloudevents/transport/http/transport.go
validate port to be in the valid port range.
fixes https://github.com/cloudevents/sdk-go/issues/48
=> validate port to be in the valid port range.

pkg/cloudevents/event_marshal.go, pkg/cloudevents/event_marshal_test.go, pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/eventcontext_v1.go, pkg/cloudevents/extensions.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/codec_v1.go
CloudEvents 1.0 only  allows attributes to be a-z0-9
Fixes: https://github.com/cloudevents/sdk-go/issues/150
Fixes: https://github.com/cloudevents/sdk-go/issues/212
=> CloudEvents 1.0 only  allows attributes to be a-z0-9

pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext_test.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/eventcontext_v1.go, pkg/cloudevents/transport/http/codec_v1.go
Fixes the propagation of DataContentEncoding for 1.0 and adding testing.
Fixes https://github.com/cloudevents/sdk-go/issues/195
=> Fixes the propagation of DataContentEncoding for 1.0 and adding testing.

pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext_v1.go, pkg/cloudevents/transport/http/codec_v1.go, pkg/cloudevents/types/doc.go, pkg/cloudevents/types/value.go, pkg/cloudevents/types/value_test.go
CloudEvents types are represented by these 6 native Go types (or canonical strings):
bool, int32, string, []byte, *url.URL, time.Time
Simple canonical string conversions following package strconv conventions:
FormatX(X) string ParseX(string)(X, error)
Where X is one of Bool, Integer, String, Binary, URL, Time:
Flex conversion: accepts any native value or canonical string and converts to native:
ToX(interface{}) (X, error)
Flex format: accepts any native value and produces the canonical string:
Format(interface{}) string
Validation: validates and converts any convertible value into one of the preferred native types. This is for internal use and for bindings with their own type-mapping rules; the binding's type switch only need consider the 6 types above, and can ignore conversions. …
=> New value conversion API (replace type Value)

pkg/cloudevents/event_test.go, pkg/cloudevents/eventcontext_v03.go, pkg/cloudevents/transport/amqp/codec.go, pkg/cloudevents/transport/http/codec_v01.go, pkg/cloudevents/transport/http/codec_v02.go, pkg/cloudevents/transport/http/codec_v03.go, pkg/cloudevents/transport/http/codec_v1.go, pkg/cloudevents/transport/pubsub/codec.go, pkg/cloudevents/types/doc.go, pkg/cloudevents/types/timestamp.go, pkg/cloudevents/types/timestamp_test.go, pkg/cloudevents/types/value.go, pkg/cloudevents/types/value_test.go
All time parsing calls types.ParseTime()
Return errors from time parsing
Added types.ConvertError error type for all conversion errors.
Improved error messages and tightened up some error handling.
=> Single point of parsing for Time

pkg/binding/doc.go, pkg/binding/example_implementing_test.go, pkg/binding/format/format.go, pkg/binding/format/format_test.go, pkg/binding/interfaces.go, pkg/binding/message.go, pkg/binding/message_test.go, pkg/binding/spec/attributes.go, pkg/binding/spec/attributes_test.go, pkg/binding/spec/doc.go, pkg/binding/spec/spec.go, pkg/binding/spec/spec_test.go, pkg/binding/transport.go
Provides string attribute names for all versions, useful for mappings
like AMQP or HTTP that use prefixed CE attribute names in their encoding.
Fixes #225
=> Package binding/spec: specversion metadata for generic mappings.

pkg/cloudevents/event_interface.go, pkg/cloudevents/eventcontext.go
Removed `// TODO: this needs to move to just string.` on Event.SetExtension It no longer needs to be a string.  Added a reference to the types documentation on EventContext.SetExtension.
=> Clarify doc comments on extensions.

pkg/cloudevents/transport/error.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go, test/http/conversion.go, test/http/conversion_v02_test.go
fixes: https://github.com/cloudevents/sdk-go/issues/175
=> allow conversion functions to not convert and not throw an error.

pkg/cloudevents/transport/http/transport.go
Allow setting the Host in the HTTP request by using the request contained in transport.
=> Allow setting Host in HTTP request

pkg/binding/chan.go, pkg/binding/doc.go, pkg/binding/interfaces.go, pkg/binding/message.go, pkg/binding/sender_test.go
Requester supports request/response pattern.
Async ack is provided by WithFinish() - Sender does async send by
default (depends on QoS and binding), WithFinish() allows the caller
to be notified when Finish() is called.
Also added ChanSender/ChanReceiver - useful for testing so might as well make
them exported.
Fixes #227
=> Added Requester and async ack support.

test/benchmark/http/README.md, test/benchmark/http/main.go, test/benchmark/http/plot_parallelism_ns.gnuplot
This benchmark emulates a typical message forwarding situation and doesn't pass through the network (the http client is mocked for this purpose), http methods are called directly and mocked.
This could be used as a comparison tool to improve further both transport/http & bindings/http
I've also included an example gnuplot script to graph the results
=> Benchmark to compare transport/http to bindings/http

.circleci/config.yml, .gitignore, alias.go, cmd/samples/simple/http/sender/main.go, go.mod, pkg/cloudevents/client/client.go, pkg/cloudevents/client/defaulters.go, pkg/cloudevents/client/defaulters_test.go, pkg/cloudevents/client/options.go
It has become a problem to not have app/json set for most users. Adding a defaulter helper and also adding it to the default client.
=> Adding client defaulter for datacontenttype = application/json.

.circleci/config.yml, go.mod, pkg/binding/test/events.go, pkg/bindings/amqp/amqp_test.go, pkg/bindings/amqp/encode.go, pkg/cloudevents/event_marshal.go, pkg/cloudevents/event_marshal_test.go, pkg/cloudevents/eventcontext.go, pkg/cloudevents/eventcontext_v1.go, pkg/cloudevents/extensions.go, pkg/cloudevents/transport/http/codec_v02_test.go, pkg/cloudevents/transport/http/codec_v03_test.go, pkg/cloudevents/transport/nats/codec_v02_test.go, pkg/cloudevents/transport/nats/codec_v03_test.go, pkg/cloudevents/transport/nats/options_test.go, pkg/cloudevents/transport/pubsub/codec_v03_test.go, pkg/cloudevents/types/value.go, pkg/cloudevents/types/value_test.go, test/http/loopback_setters_test.go
Fixes #273 
* Now extension map doesn't contain (and should not contain anymore) `net.URL` & `time.Time` (and pointers). **Users that wants to modify this map manually should keep in mind these changes**
* Unmarshalled extension types from json are now coherent between different spec versions (they are always unmarshalled as go types)
=> Fix extensions encoding

pkg/cloudevents/transport/http/transport.go
startreceiver with context cancel
when I cancel, I find the go routing func not exit, and it always get error "long poll request returned error".
=> close gorouting when context cancel

pkg/cloudevents/transport/pubsub/codec_test.go, pkg/cloudevents/transport/pubsub/codec_v1.go, pkg/cloudevents/transport/pubsub/codec_v1_test.go
- v1 should support string extensions. In the pubsub codec, we had some legacy code from 0.3, which supported maps, and other types as well.
- This caused a panic when using it from a receive adapter code, trying to decode a "int64" extension: 
panic: cannot convert 1.57947362937361e+15 to int32: out of range
Signed-off-by: Nacho Cano <nachoacano@gmail.com>
=> Fixing PubSub Codec to only support v1 string extensions 

pkg/cloudevents/transport/http/transport.go
u should check t.Client is nil or not again in mutex lock
=> Fix: defeat http.Client memory leak

.gitignore, go.sum, pkg/cloudevents/event.go, pkg/cloudevents/event_interface.go, pkg/cloudevents/event_reader_writer_test.go, pkg/cloudevents/event_writer.go
fixes: https://github.com/cloudevents/sdk-go/issues/290
Before the SDK would panic on the builder like methods for setting fields on the event as it constructed if there was a clear syntactic violation. 
This change moves the bubbling of those errors for when they call event.Validate(), the errors are assembled and sent as a single error.
A user can clear an error if they `event.Set<Field>(correctedValue)` again on the same field.
=> Rework panic out of the api.

README.md, docs/SDK_v2.md
As we are getting more adoption there is an ask for the current parts that are in heavy use be released and developed using semver. 
This documents that plan. A release of 1.0.0 is planned after this PR.
=> Document the plan for semver

alias.go, pkg/cloudevents/transport/http/context.go, pkg/cloudevents/transport/http/context_test.go
It is occasionally useful to set new headers while discarding headers
that were set for a previous request. See for example
https://github.com/knative/eventing/issues/1953.
=> Add SetContextHeaders setter.

pkg/cloudevents/transport/http/options.go
The WithMethod function was using the same docstring as the WithTarget function
=> Fix copy paste docs error

alias.go, cmd/samples/http/sender-with-custom-client/main.go, pkg/cloudevents/transport/http/options.go, pkg/cloudevents/transport/http/transport.go, pkg/cloudevents/transport/http/transport_test.go, test/benchmark/http/http_mock.go
Add a new HTTP option which allows setting the HTTP transport while
keeping the field unexported for improved safety. This change will allow
the internal HTTP client to be constructed with additional middleware
if needed, for example, for trace propagation.
=> Replace the HTTP transport Client field with unexported transport field.

pkg/cloudevents/client/client.go, pkg/cloudevents/client/observability.go
Very little work is done outside of receive/fn in the receive
observable making separate observables unnecessary.
=> Remove receive/fn observable.

cmd/samples/stats/main.go, pkg/binding/example_using_test.go, pkg/cloudevents/client/client.go, pkg/cloudevents/client/client_test.go, pkg/cloudevents/client/observability.go, pkg/cloudevents/datacodec/json/observability.go, pkg/cloudevents/datacodec/observability.go, pkg/cloudevents/datacodec/xml/observability.go, pkg/cloudevents/event_observability.go, pkg/cloudevents/extensions/distributed_tracing_extension.go, pkg/cloudevents/observability/observer.go, pkg/cloudevents/transport/http/observability.go, test/http/direct.go, test/http/loopback.go, test/http/middleware.go
This allows trace spans to be created with a different granularity
than that of Observable metrics. In particular, this commit replaces
the nested send / receive spans into a single send and receive span
created in the client. In addition, this removes spans from the encode / decode reporters which are
created without access to context making them unable to attach tracing
data to the active trace. With the reduced granularity of emitted
spans, it should now be appropriate to always enable trace
handling. As such, the EnableTracing function has been marked as
deprecated and will have no effect.
The client send and receive spans have been renamed with the prefix
"cloudevents" in order to distinguish them from send and receive spans
created by other libraries. Additionally these spans are …
=> Separate trace handling from Observable.

pkg/cloudevents/transport/http/codec.go
If a selection strategy is not chosen, the HTTP transport will chose a default codec to use regardless of the version of the event being sent. This changes the version of the default codec from 0.1 to 1.0.
See also #297.
=> Default HTTP Codec to V1

pkg/binding/spec/attributes.go, pkg/binding/spec/attributes_test.go, pkg/binding/spec/spec.go, pkg/binding/test/test.go
Now `Attribute.Name()` returns the attribute name in the specific spec version, while `Attribute.PrefixedName()` returns the prefix plus the attribute name
=> Fixed Attribute.Name()

pkg/event/eventcontext_test.go, pkg/event/eventcontext_v01.go, pkg/event/eventcontext_v02.go, pkg/event/eventcontext_v03.go, pkg/event/eventcontext_v1.go, pkg/event/eventcontext_v1_test.go, test/http/direct_v1_test.go
Fixed #332, now the `Clone()` method copies the extensions map
=> Fixed #332

pkg/binding/transport_test.go, pkg/client/client.go
This prevents the client from mutating the caller's copy of the event
allowing for sharing across multiple clients.
Fixes #350
=> Clone event context before setting the distributed tracing extension

pkg/binding/event_message.go, pkg/binding/event_message_test.go
=> Now EventMessage can be plugged to use different marshalling formats

pkg/transport/kafka_sarama/message.go, pkg/transport/kafka_sarama/message_benchmark_test.go, pkg/transport/kafka_sarama/receiver.go, pkg/transport/kafka_sarama/write_producer_message.go, pkg/transport/kafka_sarama/write_producer_message_benchmark_test.go, pkg/transport/kafka_sarama/write_producer_message_test.go, test/benchmark/http_request_to_kafka_sarama_encode/benchmark_test.go, test/benchmark/kafka_sarama_to_http_request_encode/benchmark_test.go, test/integration/kafka_sarama_binding/kafka_test.go
After discussion during Serverless WG on Thu, we figure it out that our kafka implementation is wrong. This PR removes the bad code.
=> Removed wrong implementation of the skip key extension

v2/protocol/http/protocol.go
fixes: https://github.com/cloudevents/sdk-go/issues/400
=> HTTP: set a default POST to request if template is nil

.circleci/config.yml, hack/integration-test.sh, hack/unit-test.sh
Now the code coverage correctly reports cross package code coverage (like explained here https://github.com/ory/go-acc and here https://www.ory.sh/golang-go-code-coverage-accurate/)
The CI script now puts together all coverage (from unit tests and integration tests) and generate a final report in html
=> Fixed code coverage script

v2/protocol/amqp/sender.go, v2/protocol/kafka_sarama/sender.go, v2/protocol/nats/protocol.go, v2/protocol/outbound.go, v2/protocol/test/test.go
The integration tests that uses `protocol/test.SendReceive` now correctly test this behaviour
=> Fixed various Message.Finish() invocations

v2/cmd/samples/httptonats/main.go, v2/cmd/samples/nats/receiver/main.go, v2/cmd/samples/nats/sender/main.go, v2/go.mod, v2/go.sum, v2/protocol/nats/message.go, v2/protocol/nats/options.go, v2/protocol/nats/options_test.go, v2/protocol/nats/protocol.go, v2/protocol/nats/receiver.go, v2/protocol/nats/sender.go, v2/protocol/nats/subscriber.go, v2/protocol/nats/write_message.go, v2/test/integration/nats/nats_test.go
Addresses:
- #258: You can create Consumers with the `WithQueueSubscriber("queue-name")` option
- #257: With the v2 refactor, you no longer need to wait for subscriptions to be created because calls to `Receive(ctx)` will block until either messages are received or `ctx` is closed
- #316: Follows the same pattern as kafka and STAN, with two constructors for one with an existing connection and one without.
Added integration tests for NATS, and updated the sample cmds
=> NATS protocol improvements

v1/cloudevents/extensions/distributed_tracing_extension.go, v1/cloudevents/extensions/distributed_tracing_extension_test.go, v2/extensions/distributed_tracing_extension.go, v2/extensions/distributed_tracing_extension_test.go
Also fix the following bugs which were uncovered as a result:
1. The sampled flag would not be correctly set when creating
SpanContext
2. Tracestate parsing would fail and be omitted from SpanContext
=> Fix a race condition in the distributed tracing unit tests

v2/protocol/http/write_responsewriter.go, v2/protocol/http/write_responsewriter_test.go
Before this fix, the `ResponseWriter` was writing headers *after* `WriteHeader` which, in unit tests works because `ResponseRecorder` is bugged in golang <= 1.13 (https://go-review.googlesource.com/c/go/+/178058/) and we were using it wrongly (we should perform asserts on `ResponseRecorder.Result()`).
Now the content-length is best effort: if the `io.Reader` is a reader to buffered data, content-length is written, otherwise it's not
=> Fixed ResponseWriter Content-Length and transformers

README.md, README_v1.md, v2/alias.go, v2/binding/to_event.go, v2/client/client.go, v2/client/client_observed.go, v2/client/client_test.go, v2/client/invoker.go, v2/cmd/samples/http/requester/main.go, v2/cmd/samples/httpb/requester/main.go, v2/cmd/samples/httpb/responder/main.go, v2/protocol/http/message.go, v2/protocol/http/protocol.go, v2/protocol/http/result.go, v2/protocol/http/result_test.go, v2/protocol/result.go, v2/protocol/test/test.go, v2/protocol/test/test_test.go, v2/test/integration/http/direct.go, v2/test/integration/http/loopback.go, v2/test/integration/http/middleware.go, v2/test/integration/http/responder_v1_test.go
NOTE: This is a breaking API change. client.Send and client.Receive might return a non-nil result which is an ACK.
use `cloudevents.IsACK(result)` or `protocol.IsACK(result)` to test the non-nil case.
Fixes https://github.com/cloudevents/sdk-go/issues/422
We now have the hooks for protocols to bubble up any protocol results.
=> Adding protocol.Result to Send and Request client interface.

v2/event/datacodec/codec.go, v2/event/datacodec/codec_observed.go, v2/event/datacodec/codec_test.go, v2/event/datacodec/json/data.go, v2/event/datacodec/json/data_observed.go, v2/event/datacodec/json/data_test.go, v2/event/datacodec/text/data.go, v2/event/datacodec/text/data_observed.go, v2/event/datacodec/text/data_observed_test.go, v2/event/datacodec/text/data_test.go, v2/event/datacodec/xml/data.go, v2/event/datacodec/xml/data_observed.go, v2/event/datacodec/xml/data_test.go, v2/event/event.go, v2/event/event_data.go, v2/event/event_data_test.go, v2/event/event_interface.go, v2/event/event_marshal.go, v2/event/event_marshal_test.go, v2/event/event_test.go, v2/test/integration/http/loopback_v1_test.go, v2/test/integration/http/validation.go
With this PR `datacodec` package doesn't handle the base64 encoding, this is left to the event marshaller/unmarshaller which injects into the `Data` field directly the decoded byte array.
Also improves documentation of `SetData` and `Data` explaining the various behaviours.
=> Reworking datacodec package

.circleci/config.yml, v2/alias.go, v2/binding/buffering/doc.go, v2/binding/doc.go, v2/binding/format/doc.go, v2/binding/spec/doc.go, v2/binding/transformer/doc.go, v2/client/test/test.go, v2/event/datacodec/text/data.go, v2/event/doc.go, v2/extensions/doc.go, v2/protocol/amqp/doc.go, v2/protocol/doc.go, v2/protocol/gochan/doc.go, v2/protocol/http/doc.go, v2/protocol/kafka_sarama/doc.go, v2/protocol/pubsub/context/context.go, v2/protocol/pubsub/doc.go, v2/protocol/pubsub/internal/connection.go, v2/test/benchmark/e2e/doc.go, v2/test/integration/http/doc.go
Many packages were not correctly formatting package documentation either because the documentation did not precede the package statement as required or the first line did not correctly reference the package name. A few packages were missing documentation. To prevent regressions this PR enables staticcheck ST1000 to check that every v2 package has valid package docs.
=> Fix Package Documentation and Enable Documentation Check in CircleCI

v2/client/test/mock_client.go, v2/protocol/gochan/responder.go, v2/protocol/http/protocol.go, v2/protocol/http/protocol_test.go, v2/protocol/inbound.go
Fix #433
Made explicit in the Responder godoc the lifecycle of Respond method
=> Fix Respond lifecycle in HTTP protocol

v2/binding/spec/match_exact_version.go, v2/binding/spec/match_exact_version_test.go, v2/protocol/http/headers.go, v2/protocol/http/message.go, v2/protocol/http/write_request.go, v2/protocol/http/write_responsewriter.go
Because `net/http.Header` states that headers are keyed by their canonical mime header representation (https://golang.org/pkg/net/http/#Header), I optimized on avoiding any middle allocations for accessing the attributes map and i pre-compute the header names for the various attributes.
I've also rewrote the computation of the extension key, in order to allocate only one new string.
```
benchmark                                   old ns/op     new ns/op     delta
BenchmarkHttpWithToEvent-8                  17220         15179         -11.85%
BenchmarkNoDataHttpWithToEvent-8            16575         14101         -14.93%
BenchmarkHttpWithBuffering-8                10642         8703          -18.22%
BenchmarkHttpWithDirect-8                   9080          7613          -16.16% …
```
=> Perf improvements in HTTP protocol

v2/alias.go, v2/cmd/samples/http/requester-with-custom-client/main.go, v2/cmd/samples/http/sender_retry/main.go, v2/cmd/samples/http/sleepy/main.go, v2/context/context.go, v2/context/retry.go, v2/context/retry_test.go, v2/protocol/http/protocol.go, v2/protocol/http/protocol_retry.go, v2/protocol/http/protocol_retry_test.go, v2/protocol/http/protocol_test.go, v2/protocol/http/retries_result.go, v2/protocol/http/retries_result_test.go
=> Adding Exp and Const backoff for good measure.

v2/event/event_marshal.go
There are spots in both v1 and v2 marshaling code where `unknown` is spelled with an extra `n`. This PR fixes it in v2 on the assumption that v1 error messages should not be changed.
Skipping filing an issue to save time on overhead, since I do not see a CONTRIBUTING that states a firm rule to always file first, hopefully this works for the community.
=> Fix error message spelling error: unnknown => unknown

v2/client/invoker.go
In the most MQ case, we just ack when there is no errors, but the  sdk v2 code does not transfer the ReceiverFn result context to MQ protocol `(m *Message) Finish(err error) error` method, so i add this pull request.
in my case:
```go
// The ReceiverFn
fn := func(ctx context.Context, event cloudevents.Event) protocol.Result {
// ack or nack by the event handler result
err := doSomething(event)
if err != nil {
return protocol.ResultNACK
}
if err == IgnoreError {
return protocol.ResultACK
}
return err
}
c.StartReceiver(ctx, fn)
```
in the message Finish function
```go
// Finish marks if there is no error
func (m *Message) Finish(err error) error {
if protocol.IsACK(err) {
m.internal.Ack()
} else {
m.internal.Nack()
}
return nil
}
```
the full version of kafka implement: …
=>  ack manually by the the fn result

pkg/cloudevents/extensions/distributed_tracing_extension.go, pkg/cloudevents/extensions/distributed_tracing_extension_test.go
Also fix the following bugs which were uncovered as a result:
1. The sampled flag would not be correctly set when creating
SpanContext
2. Tracestate parsing would fail and be omitted from SpanContext
Signed-off-by: Ian Milligan <ianmllgn@gmail.com>
=> Backport: Fix a race condition in the distributed tracing unit tests (#420)

v2/protocol/kafka_sarama/write_producer_message.go, v2/protocol/kafka_sarama/write_producer_message_test.go
Also splitted a part of `binding.Write` to `binding.WriteEvent`
I have implemented the mapping from `partitionkey` to Kafka Message key, but I didn't **intentionally** added any custom key mapper function, because I think this adds unnecessary complexity to the method `WriteProducerMessage`.
If the user wants a custom mapping, he can do it by itself by taking the message, converting to event, doing whatever he wants to calculate the key from the event, and then pass the event message to the `WriteProducerMessage`. Maybe there is room for the custom key mapper in the kafka sender?
Let's keep this on hold until https://github.com/cloudevents/spec/pull/599 is merged.
=> Kafka Key Mapping implementation

README.md
1. One extra brace, will cause syntax error
2. `result` not `err`
=> Correct sample in Readme

v2/protocol/pubsub/protocol.go
Fixes: https://github.com/cloudevents/sdk-go/issues/470
=> V2 pubsub protocol: don't return error if there is no error

v1/cloudevents/transport/pubsub/internal/connection.go, v1/cloudevents/transport/pubsub/internal/connection_test.go, v2/protocol/pubsub/internal/connection.go, v2/protocol/pubsub/internal/connection_test.go
Fix Issue #472 
The connection code used a sync.Once() code for Topics and Subscriptions to ensure exactly once initialization of connection state.  This had the side effect of causing future attempts to create the Topic or Subscription to fail without a retry.
This code still enforces topic/subscription initialization to be used at most once for a topic or subsciprtion, but unlinks the topic or subscription state from the underlying connection at the end of initialization if the initialization failed.
This also adds tests for these paths as well as some other paths.
=> Pubsub Topic and Subscription object creation can be retried

v2/client/client.go, v2/protocol/http/protocol.go, v2/protocol/http/protocol_test.go
Fix an issue where comparing a nil Message interface to nil would always return `false`, causing the receiver to crash.
Also respond with an error instead of OK when the message encoding can't be determined.
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 29 Apr 2020 10:18:26 GMT
Content-Length: 49
Cannot read CloudEvent: unknown Message encoding
```
Fixes #477
=> Fix comparison to nil interface

v2/client/invoker.go, v2/protocol/http/protocol.go
An error occurring during conversion from Message to Event is simply returned http BadRequest instead of causing a termination of the receiver.
```console
$ curl -D- -H "Content-Type: application/cloudevents+json" localhost:8080/ -d'{"foo": "bar"}'
HTTP/1.1 400 Bad Request
Date: Wed, 29 Apr 2020 17:14:52 GMT
Content-Length: 0
```
Closes #478
=> Return http BadRequest instead of terminating in case of conversion error

v2/cmd/samples/kafka/receiver/main.go, v2/cmd/samples/kafka/sender-receiver/main.go, v2/cmd/samples/kafka/sender/main.go, v2/protocol/kafka_sarama/protocol.go, v2/protocol/kafka_sarama/sender.go
This fixes the kafka sample applications so that you can run them. Mostly this involves setting a config version and required settings by sarama's synchronous producer.
For the sender and receiver example, I've changed it to use the same topic for receiver and sender and added a barrier to make sure the receiver has seen `count` messages before allowing the main function to exit.
=> Fix kafka samples

.circleci/config.yml, v1/cloudevents/transport/http/options_test.go, v1/cloudevents/types/value_test.go, v2/client/invoker.go, v2/client/receiver.go, v2/client/receiver_test.go, v2/cmd/samples/http/requester-with-custom-client/main.go, v2/event/event.go, v2/event/event_marshal.go, v2/event/event_marshal_test.go, v2/event/event_reader_writer_test.go, v2/event/event_test.go, v2/event/event_validation.go, v2/event/eventcontext.go, v2/event/eventcontext_v03.go, v2/event/eventcontext_v1.go, v2/protocol/http/protocol.go, v2/protocol/http/protocol_retry_test.go, v2/protocol/result.go, v2/test/integration/http/direct_v1_test.go, v2/test/integration/http/receiver.go, v2/test/integration/http/receiver_v1_test.go, v2/test/integration/http/tap_handler.go, v2/test/integration/http/validation.go
Fixes #483
To fix the problem, I had to do some changes to event validation:
* Now all event validation paths returns the strongly typed error `ValidationError`, in order to be intercepted by the http protocol
* Result caches the internal error representation
* Now the incoming event is validated
* The validation error, if exists, is returned with `text/plain` content-type
=> Correct status code replies using Client

CONTRIBUTING.md, maintainer_guidelines.md, pr_guidelines.md
This commit adds a simple contributors guide, and an in depth set of guidelines
for creating, submitting and updating pull requests. There is also a short set
of suggestions for repository maintainers in a third document.
In an effort to better organize and manage the javascript SDK, I have done this for that repository [here](https://github.com/cloudevents/sdk-javascript/pull/105). There has been [some pushback](https://github.com/cloudevents/sdk-javascript/pull/105#issuecomment-626840358) however because this is not common across all of the SDKs in the organization. I have slightly modified my pull request on the javascript SDK and submitted it here for wider discussion (even though I am not a committer on this project).
The most notable difference between this and what I have suggested …
=> docs: add contributor, maintainer and pr guides

v2/binding/format/format.go, v2/binding/format/format_test.go
Fixes #494 
Removed usage of `mime.ParseMediaType(contentType)` since it's quite expensive and we discard all the results except the first part. Part of the code is took from ParseMediaType directly
Now results are back to the previous values:
```
(c875624)⚡ % go test -benchmem -bench  . ./...
goos: linux
goarch: amd64
pkg: github.com/cloudevents/sdk-go/v2/protocol/kafka_sarama
BenchmarkNewStructuredMessage-8          	 3852535	       324 ns/op	     528 B/op	       5 allocs/op
BenchmarkNewBinaryMessage-8              	 1000000	      1033 ns/op	     953 B/op	      12 allocs/op
BenchmarkNewStructuredMessageToEvent-8   	   36049	     30915 ns/op	   11007 B/op	     171 allocs/op
BenchmarkNewBinaryMessageToEvent-8       	  279211	      4595 ns/op	    2701 B/op	      44 allocs/op …
```
=> Removed perf regression on format.Lookup

hack/integration-test.sh, hack/unit-test.sh, v2/client/client.go, v2/client/client_test.go, v2/go.mod, v2/protocol/http/options.go, v2/protocol/http/options_test.go, v2/protocol/http/protocol.go, v2/protocol/http/protocol_lifecycle.go, v2/protocol/http/protocol_test.go, v2/protocol/pubsub/internal/connection_test.go
There were two data races in client:
* Using `GetPort` for getting the actual port was racy because another goroutine is starting the listening. `GetPort` now is renamed with `GetListeningPort` for clarity and the internal `net.Listener` is behind an atomic.Value
* Trivial data race introduced by this PR https://github.com/cloudevents/sdk-go/pull/497
Enabled data race check in CI
=> Data race fix in client

README.md
The `go get` statement at the top of the README fails due to a wrongly capitalized `v`. This PR fixes that.
=> Fix Go lib version

v2/go.mod, v2/protocol/pubsub/internal/connection.go, v2/protocol/pubsub/internal/connection_test.go
Fixes #504. Fixes #509.
The test would previously timeout due to #509 so this modifies the default Receive settings to use the default number of GRPC streams defined by cloud.google.com/go/pubsub.
=> Reenable PubSub Connection Tests

protocol/stan/v2/message.go, v2/client/client.go
Fixes #527, also added ACK logic in the STAN protocol to be based off the provided `err`, which is likely a `protocol.Result`
=> 527 invalid event sigsegv

README.md
Examples are not available under ./v2/examples (anymore?), they
are in the ./examples directory, so fixing the link in the root
REAME.md.
=> Fix the link to the examples folder in the README.md

.circleci/config.yml, v2/context/context_test.go, v2/context/logger_test.go
On the CI it looks like the test is passing, but actually not.
I think this is an issue that needs to be resolved early as soon as possible for the project to proceed well.
`tee` hides the original return code.
https://github.com/cloudevents/sdk-go/blob/b276f25392c52ea8c93ef7713c817f4e5d551eb1/.circleci/config.yml#L59-L70
```
$ git checkout master
$ ./hack/unit-test.sh
...
...
PASS
coverage: 11.2%
ok  	github.com/cloudevents/sdk-go/v2/types	0.061s	coverage: 11.2%
FAIL
$ echo $?
1
```
And I fixed the test because it is normal to panic if a nil context is passed.
Follows the behavior of the standard library.
https://github.com/golang/go/blob/9f33108dfa22946622a8a78b5cd3f64cd3e455dd/src/context/context.go#L521
=> fix broken tests

v2/client/http_receiver.go, v2/client/http_receiver_test.go
Fix bug the context value set by HTTP middleware etc. was not propagated to the handler.
Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
=> fix EventReceiver does not propagate request context

v2/client/http_receiver.go, v2/protocol/http/protocol.go
fixes https://github.com/cloudevents/sdk-go/issues/537
Thanks for the repo-repo @maschmid it helped a lot to track this down. 
The root cause was the function that delegated to the ServeHTTP was exiting too soon and closing the http connection, so the bindings message to event function was attempting to read the large body out of a closed http connection, throwing an error, attempting to return a 500, but unable to do that because the ... connection was already closed. 
Adding a sync group to the standalone ServeHTTP method and also using sync.WaitGroup in the normal ServeHTTP to be consistent (I know, a little overkill, but I think it might be better than just a done channel. It gives options for batch mode in the near future.)
=> fix sync issues when using standalone http receivers

samples/amqp/sender/main.go, samples/gochan/main.go, samples/http/requester-with-custom-client/main.go, samples/http/requester/main.go, samples/http/sender-retry/main.go, samples/http/sender/main.go, samples/kafka/sender-receiver/main.go, samples/kafka/sender/main.go, samples/nats/sender/main.go, samples/pubsub/multisender/main.go, samples/pubsub/sender/main.go, samples/stan/sender-receiver/main.go, samples/stan/sender/main.go, v2/alias.go, v2/protocol/result.go
Fixes https://github.com/cloudevents/sdk-go/issues/526
No API change, just a new helper method to understand result a little better.
Old:
```go
if res := c.Send(ctx, e); !cloudevents.IsACK(res) {
log.Printf("[sender] failed to send: %v", res)
} else {
log.Printf("[sender] sent: %d", i)
}
```
Turns out, this is not true always, `!IsACK` can mean it was send and not accepted on the target side.
New:
```go
if res := c.Send(ctx, e); cloudevents.IsUndelivered(res) {
log.Printf("[sender] failed to send: %v", res)
} else {
log.Printf("[sender] sent: %d, accepted: %t", i, cloudevents.IsACK(res))
}
```
Now we can quickly understand if the event was seen by the target or not, and then test if it was accepted or not.
=> Adding IsUndelivered to help the readability of results from the protocol layers

v2/client/client.go
Using `Request` was not propagating correctly the result. This fixes it
=> Fixed wrong result propagation

protocol/kafka_sarama/v2/sender.go, protocol/kafka_sarama/v2/sender_test.go, samples/kafka/sender/main.go, v2/test/event_mocks.go
=> Added WithMessageKey to add the key to a producer message

v2/protocol/http/message_test.go, v2/protocol/http/write_request.go
Transformers which delete attributes currently fail when writing a binary message to an HTTP request with the error "invalid CloudEvents value: <nil>".
=> Fix error deleting attributes when writing to HTTP messages

samples/http/requester/main.go, samples/http/responder/main.go, test/benchmark/go.mod, test/benchmark/go.sum, test/conformance/go.mod, test/conformance/go.sum, test/integration/go.mod, test/integration/go.sum, test/integration/http/responder_v1_test.go, v2/client/client.go, v2/client/test/mock_client.go, v2/client/test/mock_client_test.go, v2/protocol/http/result.go, v2/protocol/http/result_test.go, v2/protocol/result.go, v2/protocol/result_test.go
fixes https://github.com/cloudevents/sdk-go/issues/558
I found two issues in the codebase:
1. the client was using the old style `!IsACK` to understand if it should process the response into a CloudEvent. The thinking is if it was not an ACK, then there must not be any event to parse. This logic is incorrect, it should test for `IsUndelivered`. If the event never left, then it can't have a response.
2. Nil http protocol `Result`s are not treated as ACK.
Running the `samples/http/responder` and `samples/http/requester` now get the expected output:
```
2020/07/27 14:16:18 Event sent at 2020-07-27 14:16:18.236459 -0700 PDT m=+3.540167810
2020/07/27 14:16:18 Response status code 500
Response:
Validation: valid
Context Attributes,
specversion: 1.0
type: samples.http.mod7
source: /mod7
subject: …
```
=> Fixing nil http.Result ack compare

protocol/amqp/v2/message.go, protocol/kafka_sarama/v2/message.go, protocol/pubsub/v2/message.go, v2/binding/event_message.go, v2/binding/to_event.go
Protocols which already buffer the event data can directly pass that buffer to the event created by binding.ToEvent. This change uses coercion from bytes.Buffer to skip copying the event data. Messages which do not wish to allow sharing of buffered event data, e.g. buffered messages which use a byte pool, should use bytes.Reader instead.
=> Avoid Copying Event Data When Possible in binding.ToEvent

protocol/kafka_sarama/v2/sender.go
Add NewSenderFromSyncProducer to allow running unit tests with mock sender form outside SDK
=> allow to construct mock sender for unit testing

protocol/pubsub/v2/write_pubsub_message.go
Applies the optimization from #561 to pubsub messages, allowing them to avoid copying data when given a bytes.Buffer.
=> Do not copy bytes.Buffer when writing a pubsub message

v2/client/invoker.go
Fixes https://github.com/cloudevents/sdk-go/issues/570
Logger should use `%v` instead of `%w`
=> Log: fix response log formatting

v2/client/client_default.go, v2/protocol/http/protocol.go
=> Add ochttp middleware for W3C tracecontext headers in default client

v2/client/client_default.go
In order to pass HTTP.Option into the client, I basically had to duplicate the NewDefault as seen here:
https://github.com/knative-sandbox/eventing-rabbitmq/pull/113/files#diff-e45c0bc45ea5877a2e315d983df2d17eR77
If we just allow the protocol Option optionally here (so doesn't change the signature), I could use this method as is.
WDYT?
=> pass http.Option through

v2/event/event_data_test.go, v2/event/event_marshal_benchmark_test.go, v2/event/event_marshal_test.go
Part of #609 
These benchmarks evaluates the performance of MarshalJSON() and UnmarshalJSON(), used to implement the Json Event Format
=> Benchmark Json marshal/unmarshal

v2/event/eventcontext_v1.go, v2/event/eventcontext_v1_test.go, v2/types/uri.go
Fix #615
Note: This might be seen as a breaking change because the previous validation was wrong, accepting relative uris more than absolute uris
=> URI must be absolute

v2/event/eventcontext_v1.go, v2/event/extensions.go
There's no need to use a regex for this simple check, this PR removes the regex and replaces it with a simple logic, which is a bit more efficient and allocates less
=> Remove regex to check the extension name

v2/event/event_unmarshal.go
As per title. Streams and iterators allocate a buffer to work internally, which can be reused. This does that.
The pool provided by jsoniter doesn't seem to fit our use-case, as it assumes to be passed a byte slice to read from rather than a reader.
```
benchmark                                                                                       old ns/op     new ns/op     delta
BenchmarkUnmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v1.0-16     19402         18523         -4.53%
BenchmarkUnmarshal/base64_json_encoded_data_v1.0-16                                             11628         11660         +0.28%
BenchmarkUnmarshal/nil_data_v1.0-16 …
```
=> Reduce allocations by pooling buffered JSON objects

v2/event/event_unmarshal.go
As per title.
```
benchmark                                                                                       old ns/op     new ns/op     delta
BenchmarkUnmarshal/struct_data_v0.3-16                                                          17204         16024         -6.86%
BenchmarkUnmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v0.3-16     17956         18008         +0.29%
BenchmarkUnmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v1.0-16     18128         18475         +1.91%
BenchmarkUnmarshal/string_data_v1.0-16                                                          16832         15551         -7.61%
BenchmarkUnmarshal/nil_data_v1.0-16                                                             16021         15380 …
```
=> Skip intermediary Any when needing an interface anyway

v2/event/event_unmarshal_test.go
Adds a test that catches the corner-case of having a `data_base64` as an extension in V03.
=> Add test for corner-case of having data_base64 as an extension in V03

v2/event/event_unmarshal.go
When not streaming the data, we might as well just use jsoniter's pools as intended and feed the iterator with the ready-to-go byte slice directly.
Kept the reader interface intact for enhancements on the streaming side.
```
benchmark                                                                                       old ns/op     new ns/op     delta
BenchmarkUnmarshal/struct_data_v0.3-16                                                          17204         16991         -1.24%
BenchmarkUnmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v0.3-16     17956         18042         +0.48%
BenchmarkUnmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v1.0-16     18128         17969 …
```
=> Remove intermediary reader and directly feed iterator for unmarshal

v2/event/event_unmarshal.go
Most of the keys are parsed identically between the versions, so why bother deferring their parsing and allocating stuff unnecessarily? This also puts an upper bound on the tokenQueue in theory.
```
name                                                                                old time/op    new time/op    delta
Unmarshal/struct_data_v0.3-16                                                         16.3µs ± 0%    16.4µs ± 1%   +0.75%  (p=0.032 n=5+5)
Unmarshal/nil_data_v0.3-16                                                            14.8µs ± 0%    14.9µs ± 1%   +0.73%  (p=0.016 n=5+5)
Unmarshal/struct_data_v1.0-16                                                         16.1µs ± 1%    16.3µs ± 1%     ~     (p=0.056 n=5+5) …
```
=> Only use the token queue for fields we really can't parse immediately

v2/event/event_unmarshal.go, v2/event/event_unmarshal_test.go
Having the streams in the deferred path hid a bug we had with XML handling, since they unescape when writing through them.
This moves the stream down to where it is actually needed: String based data handling. The data needs to be copied anyway, so this should also save a copy step.
```
name                                                                                old time/op    new time/op    delta
Unmarshal/string_data_v0.3-16                                                         16.1µs ± 1%    15.7µs ± 1%  -2.01%  (p=0.008 n=5+5)
Unmarshal/nil_data_v0.3-16                                                            14.9µs ± 1%    14.7µs ± 0%  -1.48%  (p=0.008 n=5+5)
Unmarshal/data,_attributes_and_extensions_and_specversion_with …
```
=> Remove writing through stream when caching data

v2/event/event_unmarshal.go
When cooking this up, I didn't realize that `ReadString` handles escaping of the string too, so the stream shenanigans are unnecessary on this path.
```
name                                                                                old time/op    new time/op    delta
Unmarshal/string_data_v0.3-16                                                         16.1µs ± 1%    15.8µs ± 1%    ~     (p=0.056 n=5+5)
Unmarshal/nil_data_v0.3-16                                                            14.9µs ± 1%    14.7µs ± 1%    ~     (p=0.056 n=5+5)
Unmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v0.3-16    16.9µs ± 0%    16.6µs ± 0%  -1.54%  (p=0.008 n=5+5) …
```
=> Drop unnecessary stream operation, reading handles escaping

v2/client/client.go, v2/go.mod, v2/protocol/http/protocol.go, v2/protocol/http/protocol_lifecycle.go
I found out while investigating #636 that the error received from `errChan` was discarded during a server shutdown. I used the occasion to wrap those errors with some additional context to ease troubleshooting a little bit.
Example:
`2020/12/08 12:55:49 Failure during runtime of CloudEvents handler: error while opening the inbound connection: combined error during shutdown of HTTP server: shutting down HTTP server: context deadline exceeded, server failed during shutdown: http: some terrible error`
=> Provide additional context in shutdown errors

README.md
Fixes #640.  Simple addition of SetID so that this code can be used as-is.
=> Add required call to SetID when marshalling JSON CloudEvent.

protocol/kafka_sarama/v2/receiver.go
https://github.com/cloudevents/sdk-go/issues/643
message is a pointer varying in the for loop, when MarkMessage is called, the pointer points to something potentially different to the current iteration
Signed-off-by: Matthieu Bernardin <matt.bernardin@gmail.com>
=> Fix Kafka ConsumeClaim loop to Mark right offset

v2/client/receiver.go
- there was missing `)` in one example.
- `transport.Result` as a return type is imho quite confusing as the `Result` type is in `protocol` package
- for consistency changed `func() error` -> `func() protocol.Result`
Signed-off-by: Zbynek Roubalik zroubali@redhat.com
=> Fix typo and change package of Result return value in fn signature

v2/binding/format/format_test.go, v2/client/client_test.go, v2/event/event_marshal.go, v2/event/event_marshal_test.go
Like #618, but from event to bytes.
A thing to notice of this streaming writer is that it writes the event fields in an order such that the parser of #618 can efficiently parse it, without buffering some fields.
Note that the marshal tests and others had to be changed because they were doing a string comparison, but the new marshaller writes the elements in a different order. Also, the unmarshalling to map uses always floats even for integers. But, semantically speaking, **there is no diff with the previous code**. 
Results:
```
name                                                                               old time/op    new time/op    delta
Marshal/number_data_v1.0-8                                                           17.1µs ± 5%     5.9µs ± 4%  -65.44%  (p=0.008 n=5+5) …
```
=> Implemented streaming writer

v2/event/event.go, v2/event/event_test.go
The reasons for this change are:
* the validation it's not related to string representation at all.
* avoid the overhead of the validation when logging events. One that needs both just invokes both methods
=> Remove validation from the string representation

protocol/stan/v2/context.go, protocol/stan/v2/context_test.go
See #657 
This is an approach which doesn't introduce any breaking changes, if users do nothing their `.Receive()` functions will receive the same `ctx` object they always have, however using the new `PropogateContext()` option will override it.
I'm going to add some comments to other parts of the codebase in this MR because I think I have an alternative approach, but needs discussion
Signed-off-by: dan-j <5727701+dan-j@users.noreply.github.com>
=> Allow stan protocol to set native *stan.Msg as a context value

protocol/amqp/v2/protocol.go, test/integration/amqp/amqp_test.go
This will resolve issue mentioned  in [656](https://github.com/cloudevents/sdk-go/issues/656)
Current  implements creates both receiver and sender amqp transport pointing to same address and causes issues as mentioned here.
The link source address of the receiver and the link target address of the transmitter are set to the same value. This means that transmitted msgs can loop back to the sender. The address uses balanced deliver so that the first msg goes to the proper destination, but the second msg loops back to sender.
This PR resolves that issue by creating separate implementation of NewProtocol as NewSenderProtocol and NewReceiver Protocol, while maintaining old implementation of NewProtocol.
=> This will resolve issue mentioned in 656

v2/event/eventcontext_v03_reader.go, v2/event/eventcontext_v03_test.go, v2/event/eventcontext_v1_reader.go, v2/event/eventcontext_v1_test.go
This PR avoids to invoke `mime.ParseMediaType` which is quite a costly method, just to grab the media type. Per https://tools.ietf.org/html/rfc7231#section-3.1.1.1, just checking for the `;` is enough. This is the same approach we use to parse the content type header in the http binding https://github.com/cloudevents/sdk-go/blob/946ebd9a535413a9cb0c2a7f910d76194a00e21a/v2/binding/format/format.go#L48
=> Remove costly parsing of content media type on the hot path

v2/event/eventcontext_v1.go, v2/event/extensions.go
I introduced a global variable `MaxExtensionNameLength` in package event, which by default is 0. If you prefer other mechanisms to globally set this value, please let me know.
As I wanted to focus on #670, I kept the changes minimal. I think that some of the functions would belong into different files now. E.g. `SetExtension()` could now go into `eventcontext_v1_writer.go`, and `extension.go` is not really needed as a separate file. 
Signed-off-by: Klaus Deissner <klaus.deissner@sap.com>
=> By default, do not restrict the length of extension attribute names

v2/protocol/http/protocol.go, v2/protocol/http/protocol_retry.go
Adding the error message to the protocol result so it can be retrieved when there are non 200 status codes.
Signed-off-by: Daniel Grist <dgrist@ibm.com>
=> Adding error to protocol result if not 200 status code

v2/protocol/http/protocol.go
Finish() no longer used binding-message in Send().  and I found that some trace mechanisms must rely on Finish() to complete.
Signed-off-by: XinYang <xinydev@gmail.com>
=> Finish() no longer used binding-message in Send()

samples/http/receiver-traced/main.go
Tracing was deprecated/turned into a noop in #634, so now this is at least a better example of how users can add tracing to an HTTP receiver.
@n3wscott
=> Update http tracing receiver sample

binding/format/protobuf/v2/datacodec.go, binding/format/protobuf/v2/protobuf.go, binding/format/protobuf/v2/protobuf_test.go
This adds the ability to send and receive protobuf encoded data within
the envelope.
=> Add protobuf datacodec

binding/format/protobuf/v2/datacodec.go, binding/format/protobuf/v2/protobuf.go, binding/format/protobuf/v2/protobuf_test.go
* Add protobuf datacodec
This adds the ability to send and receive protobuf encoded data within
the envelope.
Signed-off-by: Kevin Conway <kevinconway@invisionapp.com>
* Move pb.Any handling to protobuf format
This refactors the original protobuf datacodec so that it is generally
useful as a codec within other formats. Previously, the coded wrapped
and unwrapped every value in an Any container because this is required
when the protobuf codec and format are used together. Now, the format
handles wrapping the protobuf encoded binary data in the Any type.
Signed-off-by: Kevin Conway <kevinconway@invisionapp.com>
* Add init to register protobuf codec
Signed-off-by: Kevin Conway <kevinconway@invisionapp.com>
=> Cherry-pick: Add protobuf datacodec (#688)

v2/client/invoker.go
This way middlewares are able to mutate the message context and have that get threaded through to our invoker. Right now the context that the invoker will receive is the one passed into `StartReceiver`, which isn't as helpful.
=> Use message context as inbound context when available

observability/opencensus/v2/client/client_test.go, v2/client/client.go, v2/client/invoker.go
Call defer in the appropriate location, so the observability service callback is invoked with the error object populated. This allows to record the error into the span, or set the span as failed. 
Fixes #713
=> Propagate error to observability service

protocol/pubsub/v2/internal/connection.go, protocol/pubsub/v2/options.go, protocol/pubsub/v2/protocol.go
Signed-off-by: Iker Rejano <irejanodev@gmail.com>
=> pubsub subscription filtering support

protocol/pubsub/v2/internal/connection.go, protocol/pubsub/v2/options.go, protocol/pubsub/v2/protocol.go
My apologies, I forgot to include the filter value in the `Connection` struct to the creation method. 
This fix allows server filtering as the pubsub implementation.
CC/ @n3wscott
=> 736 feat pubsub subscription filter

v2/protocol/http/context.go, v2/protocol/http/context_test.go, v2/protocol/http/options.go, v2/protocol/http/options_test.go
Closes https://github.com/cloudevents/sdk-go/issues/742
@n3wscott this is not implemented exactly as described in the issue.
> The way I would do this is I would make a context helper in the cloudevents http package, make a new struct with these fields, copy them over before leaving the serve http method into the context using the helper context method.
Instead of adding it at the [ServeHTTP](https://github.com/cloudevents/sdk-go/blob/77f73c28a5a032a26ce0c344addc3ef4b14d60ac/v2/protocol/http/protocol.go#L285) method this PR leverages the http.Options, so this feature is an opt-in.
My main concern is that requests will hit the middleware prior to the `RateLimiter` which feels like the wrong order, but that's the case for all middlewares here. I don't consider that an issue in this PR and …
=> HTTP Protocol: add RequestData in Context option.

sql/v2/README.md, sql/v2/gen/cesqlparser_parser.go, sql/v2/go.mod, sql/v2/go.sum
Current CE SQL generated ANTLR parser throws an int overflow error on 32bit platforms, there's an open issue antlr/antlr4#2433 for it.
This PR modifies the generated parser as a workaround and adds instructions with a sed command in the development README section until the ANTLR go target gets fixed.
=> Adding workaround to an overflow error in CE SQL parser

binding/format/protobuf/v2/protobuf.go
I want to use custom API to send cloudevent to my topic, but I can't convert cloudevent objects to cloudevent proto due to private API.
hope we can make these APIs public.
=> Make SdkToProto and ProtoToSDK public

test/integration/http/blocking_test.go, v2/client/client.go, v2/client/options.go
Addresses https://github.com/cloudevents/sdk-go/issues/770 
- Add an option for the callback on receiver to be blocking or nonblocking
- Updated `blocking_test` to ensure when `pollRoutines` is `1` AND it's blocking, the events are processed in serialized manner.
Run the example receiver code: https://gist.github.com/liu-cong/a132fe8629715419c7a58ee20001d071
It retrieves the Ce-Sleep attribute from the event and sleep for that period of time.
Then send a few events to the receiver using curl, 
```shell
curl -v localhost:8080
-X POST \
-H "Ce-Sleep: 20s" \
-H "Ce-Id: 1" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: type" \
-H "Ce-Source: source" \
-H "Content-Type: application/json" \
-d '{"msg":"Test!"}
```
`cloudevents.NewClient(p, client.WithPollGoroutines(1))`
Sent 3 events, finish at the …
=> feat(client): Add option to make receive callback blocking

v2/protocol/http/protocol_retry.go, v2/protocol/http/protocol_retry_test.go, v2/protocol/http/protocol_test.go
Fixes a bug where requests with a body (event) are not always retried due to the underlying `net/http` throwing `*url.Error` because of body and content-length mismatch (body is empty and not reset upon retry). See #773 for details.
The tests did not catch this as they were not doing behaving as a real HTTP server (just mocking `RoundTripper`) and also not carrying an event body (which would not trigger this behavior). 
Closes: #773
Signed-off-by: Michael Gasch <mgasch@vmware.com>
=> Reset request body on retry

.github/workflows/go-lint.yaml
Error message:
```
level=error msg="Running error: buildir: failed to load package goarch: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version 2), export data is newer version - update tool"
```
Upgrade `golangci-lint-action` to v3 https://github.com/golangci/golangci-lint-action/issues/434
Signed-off-by: Iñigo Horcajo <inigohu@gmail.com>
=> fix golangci-lint-action

binding/format/protobuf/v2/go.mod, binding/format/protobuf/v2/go.sum, binding/format/protobuf/v2/protobuf_test.go
After much delay, I looked into https://github.com/cloudevents/sdk-go/issues/759 and concluded the go sdk is doing this correctly, and the java sdk is wrong. The output of a json marshaller is binary data, not a string, thus it should be stored in the binary field of the proto.
=> add proto test to confirm it is correct

samples/http/receiver-result/main.go, samples/http/sender-protobuf/main.go, samples/http/sender/main.go, v2/protocol/http/protocol.go
=> fix: missing error message when return HTTPResult

v2/event/event_unmarshal.go, v2/event/event_unmarshal_test.go
fixes: https://github.com/cloudevents/sdk-go/issues/782
Signed-off-by: Scott Nichols <n3wscott@chainguard.dev>
=> add unordered, unknown datacontenttype test and errors to v2/event

README.md, docs/index.md, v2/alias.go, v2/protocol/http/utility.go, v2/protocol/http/utility_test.go
Fixes #766 
This PR provides two new functions: NewEventFromHttpRequest and NewEventFromHttpResponse. Both are added to v2/alias.go, and NewEventFromHttpRequest is also demonstrated in the README and docs.
I included HttpResponse because I saw the Message methods covered it. I included docs updates because I've visited the README and docs multiple times looking for this function. Happy to remove either if they are considered unnecessary or out of scope.
Creating this PR as a draft because the test coverage I've created routinely segfaults when it begins executing the transformation logic at:
https://github.com/cloudevents/sdk-go/blob/c623f8bfd7c3d7206f0aec5730460d137e3f42a8/v2/binding/to_event.go#L61
Here is an example of how this looks on my machine:
```text
go test -v -run …
```
=> Helper function to create event from HTTP Request or Response

protocol/kafka_sarama/v2/receiver.go
Issue: https://github.com/cloudevents/sdk-go/issues/817
Issue Explanation and Fix: https://github.com/Shopify/sarama/issues/2118
Fix reference: https://github.com/Shopify/sarama/blob/5e2c2ef0e429f895c86152189f625bfdad7d3452/examples/consumergroup/main.go#L177
=> Patch sarama_kafka rebalance fix

v2/protocol/http/abuse_protection.go, v2/protocol/http/protocol_lifecycle.go
Closes #821
Signed-off-by: Doug Davis <dug@microsoft.com>
=> Add ReadHeaderTimeout for security

v2/alias.go, v2/binding/encoding.go, v2/binding/format/format.go, v2/binding/to_event.go, v2/binding/to_event_test.go, v2/protocol/http/message.go, v2/protocol/http/utility.go, v2/protocol/http/utility_test.go
Simple implementations of NewEventsFromHTTPRequest and NewEventsFromHTTPResponse as a step towards providing some support for `application/cloudevents-batch+json`.
This doesn't help with batch sending of Events, but this provides some basics of being able to process batch requests and/or responses from standard Go HTTP handling.
This could be improved over time (See previous work on #301) as well, but optimised for having something that works to start, rather than implementing big design changes.
Signed-off-by: Mark Mandel <markmandel@google.com>
=> http: Batch Events from HTTP Request and Response

README.md, docs/index.md
#835
[This pull request](https://github.com/cloudevents/sdk-go/pull/799/files) has a difference between the document and the implementation.
The document defines it as NewCloudEventFromHTTPRequest, but it is actually NewEventFromHTTPRequet.
=> Modify doc NewCloudEventFromHTTPRequest -> NewEventFromHTTPRequest

samples/http/receiver-gin/README.md, samples/http/receiver-gin/main.go
Fixes for prematurely closed #842 PR. Applied all suggested code and doc changes.
It is worth mentioning the code and instructions come from a real use case of processing Tekton events:
https://tekton.dev/docs/pipelines/events/
=> http: Fixes for Gin http receiver sample

test/integration/kafka_sarama/kafka_test.go, test/integration/kafka_sarama_binding/kafka_test.go, v2/test/event_matchers.go
resolved: https://github.com/cloudevents/sdk-go/issues/900
=> add assertion helper for extension keys

v2/protocol/http/protocol_retry.go, v2/protocol/http/protocol_retry_test.go
This PR aims to address a memory leak issue our team have observed, which was caused by the response body of messages not being closed between retries.
The consumer of binding.Message usually closes the response body by calling msg.Finish().
During retries, only the last message is returned to the consumer; so I think we should close previous message's response body via Finish() before proceeding with the next retry.
=> fix: Close response body between retries

protocol/mqtt_paho/v2/option.go, protocol/mqtt_paho/v2/protocol.go, samples/mqtt/receiver/main.go, samples/mqtt/sender/main.go, test/integration/mqtt_paho/mqtt_test.go, test/integration/mqtt_paho_binding/mqtt_test.go
Provide more flexible parameter configurations when using the MQTT protocol to send events.
=> provide publish/subscribe options for MQTT protocol

v2/client/client.go, v2/client/client_test.go, v2/client/http_receiver.go, v2/client/invoker.go, v2/client/options.go, v2/client/options_test.go
My team faced much the same issue as outlined in #757; malformed events are sent to a Kafka topic and clients endlessly fail to read the event. While this is hard to induce when the sender uses the Go CloudEvents SDK, there are a good amount of Python clients across our services which unfortunately lack validation that might prevent this.
I've elected to make this behaviour configurable via client options, as suggested in #757. This would be appropriate to use when no `protocol.Responder` implementation is available, as is the case with the `kafka_sarama` module. I explored wrapping the existing `protocol.Receiver` implementation to allow it to behave like `protocol.Responder`, but that ended up being a lot of code compared to the light touch that could be applied here.
=> Support ACK when receiving malformed events

protocol/kafka_sarama/v2/receiver.go
While analysing an issue, we observed that even after context is cancelled, the code was blocked in ConsumeClaim. And the reason is if the code if blocked at r.incoming <- msgErr, it may fail to honour or may skip the outside session.Context().Done().
Reference - https://stackoverflow.com/questions/67608032/context-ctx-done-not-being-executed-even-though-context-was-passed-to-the-functi
Solution is to add session.Context().Done() with  r.incoming <- msgErr in select clause.
=> context.Done() may never reach if waiting on r.incoming <- msgErr

protocol/mqtt_paho/v2/protocol.go, protocol/mqtt_paho/v2/write_message.go
Since we use the MQTT `Properties.User` to load the extension of the cloudevents. It can't contain the previous extension.
=> Clean up the previous user properties from MQTT protocol  

.github/workflows/integration.yaml, protocol/nats_jetstream/v2/message.go, protocol/nats_jetstream/v2/message_test.go, protocol/nats_jetstream/v2/options.go, protocol/nats_jetstream/v2/protocol.go, protocol/nats_jetstream/v2/sender.go, protocol/nats_jetstream/v2/write_message.go, test/integration/go.mod, test/integration/go.sum, test/integration/nats_jetstream/nats_test.go
Our team would like to use NATS jetstream with the cloud event-SDK. Currently binary mode is not implemented for the NATS jetstream protocol (https://github.com/cloudevents/sdk-go/issues/814). 
This PR is an enhancement to support binary-mode in the NATS jetstream protocol.
Using a binary message writer implementing MessageMetadataWriter and BinaryWriter interfaces, the cloud event headers are passed as NATS headers.  The cloud event data is pass as NATS data.
Message implements the MessageMetadataReader interface.  Also the ReadBinary() method has been implemented.
One caveat:
Due to https://github.com/cloudevents/sdk-go/blob/main/v2/binding/write.go#L91, the default now would be Binary when the context is not set due to the third if statement.
Before adding this change, there was no …
=> issue 814 - Add binary content mode for NATS and JetStream protocols

test/integration/kafka_sarama_binding/kafka_test.go
from: https://pkg.go.dev/github.com/shopify/sarama#NewConsumerGroupFromClient
- - -
NewConsumerGroupFromClient creates a new consumer group using the given client. It is still necessary to call Close() on the underlying client when shutting down this consumer. PLEASE NOTE: consumer groups can only re-use but not share clients. 
- - -
I'm not 100% sure if using the same client for sending and receiving qualifies for this restriction or not but let's see if this works w/o the "sleeps". Seems to work locally for me.
So, this PR just creates 2 clients (one for sending and one for receiving) instead of trying to reuse the same one for both.
=> Try to fix race again - don't reuse clients for sender/receiver

protocol/pubsub/v2/message.go, protocol/pubsub/v2/message_test.go
Fixes: #831 
other protocol return the error, doing similar thing here as well
=> returning the error when doing a nack in the message

protocol/pubsub/v2/attributes.go, protocol/pubsub/v2/doc.go, protocol/pubsub/v2/protocol.go, protocol/pubsub/v2/protocol_test.go, protocol/pubsub/v2/write_pubsub_message.go
Enables to pre-fill PubSub Message Attributes independent of CloudEvent spec.
Thus this allows for setting arbitrary Message Attributes (given that they are not later overwritten by CloudEvent Attributes).
=>  Add WithCustomAttributes for PubSub

binding/format/protobuf/v2/protobuf.go, binding/format/protobuf/v2/protobuf_test.go
it's improved copy of #985 - I made typo and couldn't fix previous branch
=> bugfix_value_type_of_dataschema

README.md
`log.Fatal` is mistakenly used in the following example (in the README file) which should be actually `Println` 
func main() {
// The default client is HTTP.
c, err := cloudevents.NewClientHTTP()
if err != nil {
log.Fatalf("failed to create client, %v", err)
}
log.Fatal(c.StartReceiver(context.Background(), receive));
}
=> Fixed incorrect log method in README.md

sql/v2/expression/like_expression.go, sql/v2/test/tck/README.md, sql/v2/test/tck/like_expression.yaml, sql/v2/test/tck/subscriptions_api_recreations.yaml, sql/v2/test/tck_test.go
I recently realized that the tck tests for CESQL are not up to date with the new ones added in the spec repo. This PR just copies those changes over into sdk-go, and registers the new test file.
cc @duglin @pierDipi
=> Sync CESQL tck tests

protocol/kafka_confluent/v2/option.go, protocol/kafka_confluent/v2/protocol.go, samples/kafka_confluent/receiver/main.go, samples/kafka_confluent/sender/main.go, test/integration/kafka_confluent/kafka_test.go
Resolved: https://github.com/cloudevents/sdk-go/issues/1030
=> Provide report channel `Events()` for confluent kafka producer

v2/event/datacodec/codec.go, v2/event/datacodec/codec_test.go
See #990, this adds support for encoding/decoding cloudevent data which is defined by a content-type following the [Structured Syntax Suffixes](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml) standard.
This enables the encoding/decoding of custom content types which use the `+json` or `+xml` suffix to indicate that their encoding is JSON or XML respectively. Users can also add their own suffixes to the registry in a similar fashion to how `datacodec.AddDecoder()` and `dataodec.AddEncoder()` work, but via the `AddStructuredSuffixDecoder` and `AddStructuredSuffixEncoder` functions.
Fixes #990
=> Support content types following structured syntax suffixes

v2/protocol/http/options.go, v2/protocol/http/options_test.go, v2/protocol/http/protocol.go, v2/protocol/http/protocol_lifecycle.go, v2/protocol/http/protocol_test.go
Adds options to the `Protocol` to set the `Read` and `Write` on the HTTP Client Handler for Cloud Events.
Resolves Issue: https://github.com/cloudevents/sdk-go/issues/1041
=> Allow Context to Configure Default Timeout

sql/v2/test/tck_test.go
Fixes #927 
This PR adds benchmarks to run on every TCK test case that we have, as that seemed like the easiest way of getting a good set of test cases. For each scenario, this benchmarks:
1. The parsing 
2. The evaluation
Since all these cases are already being tested for correctness, this does not bother checking if the results are correct
=> feat: added benchmarks for CESQL

sql/v2/expression/like_expression.go
This PR attempts to improve the performance of CESQL `LIKE` matches by moving away from building a regex and instead taking a simple greedy algorithm approach (which guarantees O(n+m) time complexity to consume the full string, where n is the length of the input string, and m is the length of the pattern).
This change has the added benefit of simplifying the code - we are no longer building and then evaluating a regex, simply looping over a string.
=> feat: improved performance of LIKE matching

sql/v2/parser/expression_visitor.go, sql/v2/test/tck/like_expression.yaml
Fixes #931 
When visiting the nodes of the AST while parsing the LIKE expression, it looks like we assumed that we would have a valid string literal. However, it is possible that there is no valid string literal, in which case we have to handle that and return an error rather than continuing to parse (and subsequently panicking)
=> fix: LIKE expression with invalid string literals returns a parse error instead of panicking

protocol/mqtt_paho/v2/message.go, protocol/mqtt_paho/v2/message_test.go, protocol/mqtt_paho/v2/write_message.go
Fixed: https://github.com/cloudevents/sdk-go/issues/1062
=> Fix the `content-type` issue for the MQTT protocol

v2/alias.go, v2/protocol/http/options.go, v2/protocol/http/options_test.go
Implements suggested solution #2 from [Issue #1069](https://github.com/cloudevents/sdk-go/issues/1069). 
Adds a new `WithHost` option for HTTP Protocols to enable the ability to set the HTTP `Host` header manually.
=> Add WithHost Option

protocol/pubsub/v2/message.go, protocol/pubsub/v2/message_test.go, v2/client/client.go
PUB/SUB Message acking is missing protocol.Result support.
For example, stan seems to properly handle it: https://github.com/cloudevents/sdk-go/blob/main/protocol/stan/v2/message.go#L66.
This PR fixes the issue with related tests.
Old cases supported:
| Function result                     | Acked/Nacked | Finish result       |
|-------------------------------------|--------------|---------------------|
| nil                                 | ACKED        | nil                 |
| any error | NACKED       | the original error  |
New behaviour:
| Function result                     | Acked/Nacked | Finish result       |
|-------------------------------------|--------------|---------------------|
| nil                                 | ACKED        | nil                 |
| any error except …
=> fix: pubsub ack must rely on protocol.IsAck

protocol/nats_jetstream/v2/receiver.go
I was attempting to migrate some existing code which uses longer topic names like "<software>.<subsystem>.<event-type>" to NATS Jetstream.  Unfortunately, the current code does not work for this stype of topic/subject, because:
1. Stream names cannot contain `.`.
2. The `.*` format matches a single `.`-delimited segment.
Added some logic to support both the `.>` multi-segment matcher, and using an empty string along with Consumer-side filtering.
=> Add flexibility in subject matching for nats_jetstream

.github/workflows/conformance.yaml, .github/workflows/go-build.yaml, .github/workflows/go-format.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unit-test.yaml, .github/workflows/inclusive.yaml, .github/workflows/integration.yaml, .github/workflows/observability.yaml, .github/workflows/release.yaml
Fixed the token-permission issue which is reported by the [scorecard.](https://scorecard.dev/viewer/?uri=github.com/cloudevents/sdk-go)
Part of #1087
=> Fixed the token-permission issue 

protocol/mqtt_paho/v2/protocol.go, test/integration/mqtt_paho/concurrent_test.go
Resolved: https://github.com/cloudevents/sdk-go/issues/1093
**Summary:**
**Reason:** This issue occurs when a single client sends events across multiple goroutines. Specifically, in the code here:
https://github.com/cloudevents/sdk-go/blob/1aecb204b50da7dae3d5586030c7047479334bdc/protocol/mqtt_paho/v2/protocol.go#L92-L101
at line 98, the MQTT `msg` is designed to hold a single `binding.Message` (or Event) payload. However, in a multi-goroutine environment, multiple `m` values may be written to the shared `msg`, causing a panic like `bytes.Buffer: too large`.
**Solution:** Instead of sharing the same `msg` across goroutines, we will create a copy of it each time a message is sent.
=> Fix race condition in MQTT protocol when sending messages

protocol/nats_jetstream/v3/message.go, protocol/nats_jetstream/v3/message_test.go, protocol/nats_jetstream/v3/options.go, protocol/nats_jetstream/v3/options_test.go, protocol/nats_jetstream/v3/protocol.go
In some cases, an explicit ACK/NACK may be necessary.  Currently, there is no way to NACK a message.  Also, in some cases, the NATS server may not automatically ACK a message.
This logic explicitly looks for an error that is `protocol.ResultNACK`, for when to do a `Nak`.  
If the error is `nil` or `protocol.ResultACK`, then a `Ack` is done.
When an unknown error occurs, the original behavior of `return nil` is invoked.
Testing with a live system can be done by temporarily modifying:
https://github.com/cloudevents/sdk-go/blob/main/v2/protocol/test/test.go#L41
that is called from:
https://github.com/cloudevents/sdk-go/blob/main/test/integration/nats_jetstream/v3/nats_test.go#L29
=> Add NATS Ack/Nak to nats jetstream V3 Finish

v2/event/event_marshal.go, v2/event/event_marshal_test.go
This PR proposes to make JSON serialization deterministic, i.e., always produce the same result for the same input. This matches Go's behavior for built-in types, which notably will explicitly [sort](https://github.com/golang/go/blob/40b3c0e58a0ae8dec4684a009bf3806769e0fc41/src/encoding/json/encode.go#L762) fields within a map when serializing.
v2/event/event_marshal.go's `WriteJson`'s only non-deterministic behavior is an iteration over a map of extensions, which is performed in random order. This PR takes a similar [approach](https://github.com/golang/go/blob/40b3c0e58a0ae8dec4684a009bf3806769e0fc41/src/encoding/json/encode.go#L762) as `encoding/json`, without their logic for "resolving" key names (since extension names are always strings), and without the use of `reflect.Value`.
The …
=> Sort extensions during JSON serialization

v2/event/event_unmarshal.go, v2/event/event_unmarshal_test.go
=> need to json.unmarshal data_base64

v2/extensions/dataref_extension.go, v2/extensions/dataref_extension_test.go
Inspired by the java sdk, adding a go implementation  for `dataref` extension
Fixes #198
=> Adding a simple dataref extension

protocol/nats_jetstream/v3/protocol.go, protocol/nats_jetstream/v3/protocol_test.go, samples/nats_jetstream/v3/receiver/main.go, samples/nats_jetstream/v3/sender/main.go
I had some issues with a single subject regardless of event. Added a function to add an alternate subject via context.
This will also possibly close #1115
=> fix: make send subject optional via context

.github/workflows/conformance.yaml, .github/workflows/go-build.yaml, .github/workflows/go-format.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unit-test.yaml, .github/workflows/integration.yaml, .github/workflows/observability.yaml, .github/workflows/release.yaml, .github/workflows/update-dependencies.yml, README.md
Addresses an issue with https://github.com/cloudevents/sdk-go/actions/runs/17366826821 due to `go: google.golang.org/genproto@v0.0.0-20250826171959-ef028d996bc1 requires go >= 1.24.0 (running go 1.23.12)`
=> Update Go version in workflows

.github/workflows/integration.yaml
Cannot use github actions `services` during CI because of limitation in github actions in supplying  `-js` argument to container
=> switch from bitnami nats to nats:latest for jetstream
