- README.md
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
> Correcting Knative CloudEVent SDK location

- README.md
some typo in the old/update readme 
ping @tenczar
> Using the marshaller

- README.md
> fix readme with new client example.

- pkg/cloudevents/codec/codec_test.go
- pkg/cloudevents/transport/codec_test.go
> Adding nop tests to make coverage show real results for empty dirs.

- README.md
- cmd/samples/complex/httptonats/main.go
- cmd/samples/complex/sender/main.go
- cmd/samples/http/receiver/main.go
- cmd/samples/http/sender/main.go
- cmd/samples/nats/receiver/main.go
- cmd/samples/nats/sender/main.go
- pkg/cloudevents/client/client_http.go
Got some more review on the usage of context, cleaned up.
> Clean up Contexts.

- cmd/samples/complex/httptonats/main.go
- cmd/samples/complex/sender/main.go
- cmd/samples/http/sender/main.go
- cmd/samples/nats/sender/main.go
- pkg/cloudevents/client/client.go
- pkg/cloudevents/client/client_http.go
- pkg/cloudevents/client/client_nats.go
- pkg/cloudevents/client/options.go
- pkg/cloudevents/client/options_test.go
- pkg/cloudevents/transport/http/transport.go
Adding tests to client. Moving to a Client interface to support injection of test clients in consumer libs.
> Adding test coverage of Client. Move Client to interface.

- README.md
> Add context to new encoder options, also ran prettier.

- pkg/cloudevents/client/client.go
"initalized" to "initialized".
> Fix fmt.Errorf() error message

- .circleci/config.yml
- pkg/cloudevents/codec/codec_test.go
- pkg/cloudevents/transport/codec_test.go
Add an initial circleci configuration to automate testing for PR's and showing test results.
> Add circleci configuration for test automation

- pkg/cloudevents/client/client_test.go
- pkg/cloudevents/context/context_test.go
- pkg/cloudevents/transport/http/context_test.go
> Fix a bad merge.

- README.md
Fixes https://github.com/cloudevents/sdk-go/issues/75
I missed updating the README on the last API change. Sorry.
> Fix Readme to 0.4.0 api.

- pkg/cloudevents/transport/http/options.go
- pkg/cloudevents/transport/http/options_test.go
- pkg/cloudevents/transport/http/transport.go
Feature request while integrating with Knative Eventing.
> Adding http transport Shutdown Timeout

- README.md
> Adding go report card.

- cmd/samples/http/responder/main.go
- cmd/samples/http/sender/main.go
- cmd/samples/simple/http/sender/main.go
- pkg/cloudevents/event_response.go
- pkg/cloudevents/transport/http/context.go
- pkg/cloudevents/transport/http/transport.go
Fixes https://github.com/cloudevents/sdk-go/issues/61
> Adding headers to send+response.

- pkg/cloudevents/client/options.go
- pkg/cloudevents/datacodec/json/doc.go
- pkg/cloudevents/datacodec/xml/doc.go
- pkg/cloudevents/eventcontext.go
- pkg/cloudevents/observability/doc.go
- pkg/cloudevents/observability/keys.go
- pkg/cloudevents/observability/observer.go
- pkg/cloudevents/transport/http/codec.go
- pkg/cloudevents/transport/http/codec_v01.go
- pkg/cloudevents/transport/http/codec_v02.go
- pkg/cloudevents/transport/http/codec_v03.go
- pkg/cloudevents/transport/http/context.go
- pkg/cloudevents/transport/http/doc.go
- pkg/cloudevents/transport/http/encoding.go
- pkg/cloudevents/transport/http/options.go
- pkg/cloudevents/transport/http/transport.go
- pkg/cloudevents/transport/message.go
- pkg/cloudevents/transport/nats/doc.go
- pkg/cloudevents/transport/nats/encoding.go
- pkg/cloudevents/transport/nats/options.go
- pkg/cloudevents/transport/nats/transport.go
- pkg/cloudevents/types/allocate.go
Adding go report and noticed a bunch of issues. Trying to fix some of those.
> Fixing lint errors.

- pkg/cloudevents/event.go
- pkg/cloudevents/event_test.go
- pkg/cloudevents/eventcontext.go
- pkg/cloudevents/eventcontext_v01.go
- pkg/cloudevents/eventcontext_v02.go
- pkg/cloudevents/eventcontext_v03.go
**Proposed Changes**
- Adding Source() and SchemaURL() to Event.
- Adding GetSource() and GetSchemaURL() to EventContext interface.
- Adding UTs.
> Adding Getters for Source and SchemaURL

- README.md
> Adding release and license tags.

- pkg/cloudevents/codec/codec_test.go
- pkg/cloudevents/codec/jsoncodec.go
- pkg/cloudevents/eventcontext.go
- pkg/cloudevents/eventcontext_v01_reader.go
- pkg/cloudevents/eventcontext_v02.go
- pkg/cloudevents/eventcontext_v02_reader.go
- pkg/cloudevents/eventcontext_v03.go
- pkg/cloudevents/eventcontext_v03_reader.go
- pkg/cloudevents/transport/http/codec_v02.go
- pkg/cloudevents/transport/http/codec_v02_test.go
- pkg/cloudevents/transport/http/codec_v03.go
- pkg/cloudevents/transport/http/codec_v03_test.go
- pkg/cloudevents/transport/nats/codec_v02_test.go
- pkg/cloudevents/transport/nats/codec_v03_test.go
- test/http/loopback_setters_test.go
fixes https://github.com/cloudevents/sdk-go/issues/95
> Follow CloudEvent Spec for >v0.2 structured extensions

- pkg/cloudevents/event_data.go
- pkg/cloudevents/event_data_test.go
- pkg/cloudevents/transport/http/transport.go
- test/http/loopback_setters_test.go
Found the get bytes method throws an error if there are no bytes to decode. No bytes is a valid option, return back nothing, not an error.
> fix no data bug.

- alias.go
- cmd/longpollserver/main.go
- cmd/samples/simple/http/longpollreceiver/main.go
- pkg/cloudevents/client/client_test.go
- pkg/cloudevents/transport/error.go
- pkg/cloudevents/transport/http/context.go
- pkg/cloudevents/transport/http/options.go
- pkg/cloudevents/transport/http/options_test.go
- pkg/cloudevents/transport/http/transport.go
- pkg/cloudevents/transport/http/transport_test.go
We identified a new class of receivers that is a do poll-based event receiving. Adding that to the http client.
> Adding long poll support for http.Receive.

- pkg/cloudevents/transport/transport.go
This is analogous to http.HandleFunc which makes a http.Handler
from a function.
> Add ReceiveFunc wrapper - make Receiver from function.

- cmd/samples/pubsub/converter/receiver/main.go
- cmd/samples/pubsub/receiver/main.go
- pkg/cloudevents/event_data_test.go
- pkg/cloudevents/event_marshal.go
- pkg/cloudevents/eventcontext_v01.go
- pkg/cloudevents/eventcontext_v02.go
- pkg/cloudevents/eventcontext_v03.go
- pkg/cloudevents/types/timestamp.go
- pkg/cloudevents/types/urlref.go
I spotted a couple of misspellings in the code and thought I'd fix them up. Some of them appear on go report card. Not sure on the contribution guidelines for the repo, but hope this helps.
> Fix various misspellings

- pkg/cloudevents/client/client.go
- pkg/cloudevents/client/defaulters.go
- pkg/cloudevents/client/defaulters_test.go
- pkg/cloudevents/client/options_test.go
- test/http/loopback.go
> Wire up context to event defaults.

- pkg/cloudevents/transport/http/transport.go
> fix a syntax error in a logw line.

- pkg/cloudevents/transport/pubsub/transport.go
I had a debug statement in the pubsub receive adapter code. Removed.
> Leaked a debug line.

- alias.go
Signed-off-by: Celso Santos <zedblade.santos@gmail.com>
> Adds WithListener to alias list

- pkg/cloudevents/event_marshal.go
- pkg/cloudevents/eventcontext.go
- pkg/cloudevents/eventcontext_v01_reader.go
- pkg/cloudevents/eventcontext_v02_reader.go
- pkg/cloudevents/eventcontext_v03_reader.go
- pkg/cloudevents/eventcontext_v1_reader.go
- pkg/cloudevents/extensions.go
- pkg/cloudevents/transport/http/codec_v1.go
- pkg/cloudevents/transport/http/codec_v1_test.go
> Revert back to interface for extensions.

- pkg/cloudevents/eventcontext_v03.go
- pkg/cloudevents/eventcontext_v1.go
- pkg/cloudevents/eventcontext_v1_writer.go
> Fix version typo in eventcontext_v03.

- pkg/binding/format/format_test.go
- pkg/binding/message_test.go
> Remove datacontent attr

- pkg/cloudevents/datacodec/codec.go
- pkg/cloudevents/datacodec/codec_test.go
- pkg/cloudevents/datacodec/text/text.go
- pkg/cloudevents/datacodec/text/text_test.go
> Add datacodec support for "text/plain" media type.

- test/http/loopback_v03_test.go
- test/http/loopback_v1_test.go
fixes:  https://github.com/cloudevents/sdk-go/issues/222
> adding tests to confirm base64 data is working.

- test/http/middleware.go
- test/http/middleware_v1_test.go
fixes: https://github.com/cloudevents/sdk-go/issues/209
Can not repro the issue with the test.
> Adding middleware test for number parsing.

- pkg/cloudevents/transport/nats/codec.go
- pkg/cloudevents/transport/nats/codec_v1.go
- pkg/cloudevents/transport/nats/codec_v1_test.go
- pkg/cloudevents/transport/nats/encoding.go
- pkg/cloudevents/transport/nats/transport.go
fixes: https://github.com/cloudevents/sdk-go/issues/242
> Adding NATS 1.0 support.

- pkg/cloudevents/transport/amqp/encoding.go
- pkg/cloudevents/transport/amqp/message.go
- pkg/cloudevents/transport/amqp/transport.go
fixes: https://github.com/cloudevents/sdk-go/issues/243
> Expose AMQP 1.0 via sdkv1

- pkg/cloudevents/transport/pubsub/codec.go
- pkg/cloudevents/transport/pubsub/codec_v1.go
- pkg/cloudevents/transport/pubsub/codec_v1_test.go
- pkg/cloudevents/transport/pubsub/encoding.go
fixes: https://github.com/cloudevents/sdk-go/issues/241
> Adding pubsub codecs for 1.0

- pkg/binding/test/test.go
Handle case where Send() returns an error and therefore Receive() is never called.
> Fix deadlock in test.SendRecieve

- cmd/samples/pubsub/multisender/main.go
- cmd/samples/pubsub/sender/main.go
- pkg/cloudevents/transport/pubsub/codec.go
- pkg/cloudevents/transport/pubsub/codec_test.go
- pkg/cloudevents/transport/pubsub/codec_v03.go
- pkg/cloudevents/transport/pubsub/codec_v03_test.go
- pkg/cloudevents/transport/pubsub/codec_v1.go
- pkg/cloudevents/transport/pubsub/codec_v1_test.go
- pkg/cloudevents/transport/pubsub/encoding.go
- fix v1 transport, set default encoding
- apply refactors from http tranport
- update pubsub transport examples to use v1
Closes #255
> pubsub: fix v1 transport, default encoding, refactors

- test/benchmark/benchmark_case.go
- test/benchmark/benchmark_result.go
- test/benchmark/http/3d_plot_allocs.gnuplot
- test/benchmark/http/3d_plot_ns.gnuplot
- test/benchmark/http/http_mock.go
- test/benchmark/http/main.go
- test/benchmark/http/plot_output_senders_allocs.gnuplot
- test/benchmark/http/plot_output_senders_ns.gnuplot
- test/benchmark/http/plot_parallelism_allocs.gnuplot
- test/benchmark/http/plot_parallelism_ns.gnuplot
- test/benchmark/http/run_revision.sh
> Improving HTTP benchmark for comparing various bindings 

- README.md
Signed-off-by: Doug Davis <dug@us.ibm.com>
> initial template for more helpful info for newbies

- pkg/cloudevents/extensions/distributed_tracing_extension.go
- pkg/cloudevents/extensions/distributed_tracing_extension_test.go
Implements the distributed tracing extension.
closes #199
> Add distributed tracing extension and its test cases  (#1)

- .circleci/config.yml
- hack/presubmit-test.sh
- pkg/bindings/amqp/encoder.go
- pkg/bindings/amqp/receiver.go
- pkg/cloudevents/transport/amqp/transport_test.go
Also added verbose flag to tests
> Added AMQP Router to CircleCI

- hack/presubmit-test.sh
- pkg/bindings/amqp/amqp_test.go
- pkg/cloudevents/transport/amqp/transport_test.go
> Disabled parallel test executions for amqp tests

- README.md
- pkg/cloudevents/event.go
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
> default version was set to 1.0 some time ago

- README.md
Adding a note to the readme to explain how branches are expected to be used in the future.
> Detail the 1.1 support plan

- pkg/bindings/http/message.go
- pkg/bindings/http/message_test.go
> Fixed http/Message.Encoding() which was reporting the wrong encoding

- pkg/binding/transcoder/add_or_update_metadata_test.go
> Fix bad merge

- pkg/binding/event_message.go
- pkg/binding/spec/attributes_test.go
- pkg/binding/spec/spec.go
- pkg/binding/spec/spec_test.go
- pkg/binding/test/mock_binary_message.go
- pkg/binding/test/test.go
- pkg/binding/transformer/add_metadata.go
- pkg/binding/transformer/delete_metadata.go
- pkg/binding/transformer/update_metadata.go
- pkg/bindings/amqp/message.go
- pkg/bindings/http/message.go
- pkg/bindings/kafka_sarama/message.go
> Removed specs.FindVersion()

- pkg/binding/message.go
- pkg/transport/bindings/transport.go
- pkg/transport/http/message.go
- pkg/transport/http/protocol.go
- pkg/transport/http/protocol_server.go
- pkg/transport/responder.go
> Adding Responder interface, removing ResponseMessage

- go.mod
- go.sum
- pkg/binding/buffering/copy_message_test.go
- pkg/binding/test/test.go
- pkg/binding/test/transformer.go
- pkg/binding/to_event_test.go
- pkg/binding/transformer/add_metadata_test.go
- pkg/binding/transformer/default_metadata_test.go
- pkg/binding/transformer/delete_metadata_test.go
- pkg/binding/transformer/set_metadata_test.go
- pkg/binding/transformer/update_metadata_test.go
- pkg/binding/transformer/version_test.go
- pkg/event/event.go
- pkg/event/event_test.go
- pkg/event/eventcontext_test.go
- pkg/event/eventcontext_v03.go
- pkg/event/eventcontext_v1.go
- pkg/transport/http/message_write_response_test.go
- pkg/types/value.go
- pkg/types/value_test.go
> Event clone

- cmd/samples/kafka/receiver/main.go
- cmd/samples/kafka/sender/main.go
- cmd/samples/kafka/sender_and_receiver/main.go
- pkg/client/test/test.go
- pkg/transport/kafka_sarama/message_benchmark_test.go
- pkg/transport/kafka_sarama/option.go
- pkg/transport/kafka_sarama/protocol.go
- pkg/transport/kafka_sarama/receiver.go
- pkg/transport/kafka_sarama/sender.go
- test/integration/kafka_sarama/kafka_test.go
- test/integration/kafka_sarama_binding/kafka_test.go
* Implemented Kafka protocol
* Splitted Kafka `Receiver` in `Receiver` (which implements `transport.Receiver`) and `Consumer` (which implements `transport.Opener`)
> Refactored Kafka transport

- alias.go
- cmd/samples/http/receiver-traced/main.go
- cmd/samples/httpb/responder/main.go
- pkg/client/client_observed.go
- pkg/client/client_test.go
- pkg/client/invoker.go
- pkg/client/observability.go
- pkg/client/options.go
- pkg/extensions/distributed_tracing_extension.go
- pkg/extensions/distributed_tracing_extension_test.go
- pkg/observability/keys.go
- test/integration/http/direct.go
- test/integration/http/loopback.go
- test/integration/http/middleware.go
> Adding trace support back in.

- alias.go
- cmd/samples/httpb/responder/main.go
- legacy/pkg/binding/transcoder.go
- legacy/pkg/bindings/amqp/encoder.go
- pkg/binding/buffering/copy_message.go
- pkg/binding/buffering/copy_message_test.go
- pkg/binding/test/test.go
- pkg/binding/test/transformer.go
- pkg/binding/to_event.go
- pkg/binding/to_event_test.go
- pkg/binding/transformer.go
- pkg/binding/write.go
- pkg/client/client.go
- pkg/client/invoker.go
- pkg/protocol/amqp/write_message.go
- pkg/protocol/http/write_request.go
- pkg/protocol/http/write_responsewriter.go
- pkg/protocol/http/write_responsewriter_test.go
- pkg/protocol/kafka_sarama/message_benchmark_test.go
- pkg/protocol/kafka_sarama/write_producer_message.go
- pkg/protocol/kafka_sarama/write_producer_message_test.go
- pkg/protocol/nats/write_message.go
- Add missing alias imports
- Moving to var-arg transformers
> Add missing alias imports; Moving to var-arg transformers

- v2/binding/event_message_test.go
- v2/binding/test/mock_unknown_message.go
- v2/binding/to_event.go
- v2/binding/to_event_test.go
> Increasing coverage of EventMessage and ToEvent

- v2/test/doc.go
- v2/types/timestamp_test.go
- v2/types/value.go
- v2/types/value_test.go
> Adding unit tests to increate around the types package.

- v2/protocol/http/write_request.go
> write out content length for http request

- v2/protocol/kafka_sarama/message.go
- v2/protocol/kafka_sarama/message_benchmark_test.go
- v2/protocol/kafka_sarama/message_test.go
- v2/protocol/kafka_sarama/write_producer_message_test.go
> Added NewMessage test for Kafka

- v2/alias.go
- v2/cmd/samples/http/requester-with-custom-client/main.go
- v2/protocol/amqp/protocol.go
- v2/protocol/http/message.go
- v2/protocol/http/message_test.go
- v2/protocol/http/options.go
- v2/protocol/http/options_test.go
- v2/protocol/http/protocol.go
- v2/protocol/http/protocol_lifecycle.go
- v2/protocol/http/protocol_test.go
- v2/protocol/http/result.go
- v2/protocol/http/result_test.go
- v2/protocol/kafka_sarama/protocol.go
- v2/protocol/result_test.go
- v2/test/benchmark/e2e/http/http_mock.go
More to add, but this was able to uncover a few corner cases where we could get stuck.
> Adding unit tests for http.

- v2/binding/spec/attributes.go
- v2/binding/to_event.go
- v2/binding/to_event_test.go
- v2/event/event_marshal.go
- v2/event/event_reader_writer_test.go
- v2/event/event_test.go
- v2/event/event_writer.go
- v2/event/eventcontext.go
- v2/event/eventcontext_test.go
- v2/event/eventcontext_v03.go
- v2/event/eventcontext_v03_reader.go
- v2/event/eventcontext_v03_test.go
- v2/event/eventcontext_v03_writer.go
- v2/event/eventcontext_v1.go
- v2/event/eventcontext_v1_reader.go
- v2/event/eventcontext_v1_test.go
- v2/event/eventcontext_v1_writer.go
> Removed SpecVersion from EventContextV1 and EventContextV03

- v2/cmd/samples/httptonats/main.go
> Refactored httptonats example to use directly the protocols

- v2/protocol/http/message_test.go
- v2/protocol/http/write_responsewriter_test.go
> Added direct piping test & buffering test for http.WriteResponseWriter

- v2/event/event_marshal.go
- v2/event/event_marshal_test.go
- v2/event/eventcontext_v03.go
- v2/event/eventcontext_v1.go
- v2/protocol/doc.go
- v2/protocol/http/message.go
- v2/protocol/http/protocol.go
- v2/protocol/stan/receiver.go
- v2/test/benchmark/e2e/http/main.go
- v2/types/uri_test.go
- v2/types/uriref_test.go
- v2/types/value_test.go
* Added a test for #60
* Fixed RoundTripper usage in http.Protocol
* Fixed DataContentType validation in 0.3
> Removed irrelevant TODOs

- v2/protocol/pubsub/message.go
- v2/protocol/pubsub/protocol.go
Fix: https://github.com/cloudevents/sdk-go/issues/429
> Fix Pubsub protocol to properly ack/nack received messages

- README.md
Signed-off-by: Ian Milligan <ianmllgn@gmail.com>
> Fix v2 README links

- v2/protocol/kafka_sarama/protocol.go
> Kafka Transport uses senderTransformers

- v2/client/observability.go
> Added ID to EventTraceAttributes

- v2/extensions/distributed_tracing_extension.go
- v2/extensions/distributed_tracing_extension_test.go
> Added transformers to read and write DistributedTracing extension

- v2/protocol/http/message.go
- v2/protocol/http/message_test.go
> Hotfix for http message headers

- v2/binding/buffering/acks_before_finish_message.go
- v2/binding/buffering/acks_before_finish_message_test.go
- v2/binding/finish_message.go
- v2/binding/finish_message_test.go
> Hotfix for MessageWrapper

- v2/cmd/samples/amqp/receiver/main.go
- v2/cmd/samples/amqp/sender/main.go
- v2/go.mod
- v2/go.sum
- v2/protocol/amqp/message.go
- v2/protocol/amqp/message_test.go
- v2/protocol/amqp/options.go
- v2/protocol/amqp/protocol.go
- v2/protocol/amqp/receiver.go
- v2/protocol/amqp/sender.go
- v2/protocol/amqp/write_message.go
- v2/test/integration/amqp/amqp_test.go
- v2/test/integration/amqp_binding/amqp_test.go
> Replaced the amqp dep

- v2/binding/transformer/default_metadata.go
- v2/binding/transformer/default_metadata_test.go
- v2/protocol/amqp/options.go
- v2/protocol/amqp/protocol.go
- v2/protocol/amqp/sender.go
- v2/protocol/gochan/requester.go
- v2/protocol/gochan/responder.go
- v2/protocol/gochan/sender.go
- v2/protocol/http/protocol.go
- v2/protocol/http/protocol_test.go
- v2/protocol/inbound.go
- v2/protocol/kafka_sarama/option.go
- v2/protocol/kafka_sarama/protocol.go
- v2/protocol/kafka_sarama/sender.go
- v2/protocol/nats/options.go
- v2/protocol/nats/options_test.go
- v2/protocol/nats/protocol.go
- v2/protocol/nats/sender.go
- v2/protocol/nats/write_message.go
- v2/protocol/outbound.go
- v2/protocol/pubsub/protocol.go
- v2/protocol/stan/options.go
- v2/protocol/stan/options_test.go
- v2/protocol/stan/protocol.go
- v2/protocol/stan/sender.go
- v2/protocol/test/test_test.go
Fixes #451
Also removes `transformer.SetUUID`
> Now Send/Request/ResponseFn accept transformers

- README.md
- docs/_config.yml
- docs/concepts.md
- docs/event_data_structure.md
- docs/index.md
- docs/protocol_implementations.md
> Working on website

- v2/client/client.go
- v2/protocol/kafka_sarama/receiver.go
- v2/test/integration/kafka_sarama/kafka_test.go
- v2/test/integration/kafka_sarama_binding/kafka_test.go
Fix https://github.com/cloudevents/sdk-go/pull/487
> Fixed consumer group usage

- .gitignore
- docs/_config.yml
> Fixed docs

- docs/_config.yml
- docs/index.md
- docs/protocol_implementations.md
Also reworded the first part of protocol_implementations.md page
> Added some missing links to the website

- v2/binding/finish_message_test.go
- v2/binding/message.go
- v2/cmd/samples/README.md
- v2/cmd/samples/kafka/sender/main.go
- v2/cmd/samples/message-handle-non-cloudevents/main.go
Added sample that shows how to handle non cloudevents, as discussed in #483
> Added UnwrapMessage method

- v2/client/client.go
- v2/client/options.go
> Implemented parallelism in client polling

- v2/extensions/distributed_tracing_extension.go
> Fix Distributed Tracing Extension WriteTransformer

- v2/protocol/http/result.go
- v2/protocol/http/result_test.go
Fix: https://github.com/cloudevents/sdk-go/issues/510
> Fix error print in http protocol result

- docs/Gemfile
- docs/Gemfile.lock
> Dump jekyll version

- protocol/pubsub/v2/message.go
- protocol/pubsub/v2/message_test.go
Fix a nil pointer bug, also add basic testing.
This bug caused panic in GCP broker: https://github.com/google/knative-gcp/issues/1178
> Fix pubsub message nil pointer due to missing format

- v2/test/event_asserts_test.go
- v2/test/event_matchers.go
Makes less verbose the attributes checking
> Modified a bit the assertions from #522

- v2/test/event_asserts_test.go
- v2/test/event_matchers.go
- v2/test/event_matchers_test.go
- AnyOf
- DataContains
- ContainsExactlyExtensions
- HasExactlyAttributesEqualTo
> Added new matchers

- .github/workflows/draft-release.yaml
> fix gh action from api change.

- .github/workflows/draft-release.yaml
- RELEASING.md
- hack/tag-release.sh
fixes https://github.com/cloudevents/sdk-go/issues/525
I wrote down everything I did and automated for the release process.
> Document the release process used for v2.1.0

- README.md
Fixes instructions in README for JSON parsing a CloudEvent
> fix JSON unmarshal instructions in README.md

- v2/event/event_validation.go
fix a bug which can cause invalid event to pass validation
> [Validation] fix event validation bug

- README.md
- RELEASING.md
- docs/index.md
- hack/tag-release.sh
> update readme and releasing files post-release.

- v2/protocol/gochan/protocol.go
> Fix gochan sender

- v2/protocol/http/protocol_retry.go
- v2/protocol/http/protocol_retry_test.go
Modify the logic so it's a bit easier to add new ones
Closes: #578
Signed-off-by: Doug Davis <dug@us.ibm.com>
> Add retry for 502's

- protocol/pubsub/v2/protocol.go
fixes #580
Signed-off-by: Iñigo Horcajo <inigohu@gmail.com>
> Fix pubsub protocol context cancellation

- test/integration/http/blocking_test.go
- test/integration/http/receiver_v1_test.go
- v2/client/invoker.go
> Recover from panic in handler fn

- v2/client/receiver.go
- v2/client/receiver_test.go
Input types should be contravariant or invariant.
> Fix handler input types variance

- .github/workflows/conformance.yaml
- .github/workflows/go-build.yaml
- .github/workflows/go-unit-test.yaml
- .github/workflows/integration.yaml
- README.md
- hack/integration-test.sh
- protocol/amqp/v2/go.mod
- protocol/amqp/v2/go.sum
- protocol/kafka_sarama/v2/go.mod
- protocol/kafka_sarama/v2/go.sum
- protocol/nats/v2/go.mod
- protocol/nats/v2/go.sum
- protocol/pubsub/v2/go.mod
- protocol/pubsub/v2/go.sum
- protocol/stan/v2/go.mod
- protocol/stan/v2/go.sum
- samples/amqp/go.mod
- samples/gochan/go.mod
- samples/http/go.mod
- samples/kafka/go.mod
- samples/nats/go.mod
- samples/pubsub/go.mod
- samples/stan/go.mod
- test/benchmark/go.mod
- test/conformance/go.mod
- test/integration/go.mod
- tools/go.mod
- v2/go.mod
- v2/protocol/result.go
> bumping the golang min version to go 1.14

- protocol/kafka_sarama/v2/receiver.go
> Fix kafka consumer OpenInbound loop

- v2/protocol/http/options.go
- v2/protocol/http/options_test.go
- v2/protocol/http/protocol.go
- v2/protocol/http/protocol_retry.go
- v2/protocol/http/protocol_retry_test.go
- v2/protocol/http/protocol_test.go
Fixes #595 
Introduce an option for overriding the retry policy.
> add ability to specify custom func for retry policy

- protocol/pubsub/v2/go.mod
- protocol/pubsub/v2/protocol.go
> Use errgroup to wait for subscribers in OpenInbound

- v2/event/event_unmarshal.go
As per title. This makes the code a bit more simple and avoids a few allocations. YAY?
```
benchmark                                                                                       old ns/op     new ns/op     delta
BenchmarkUnmarshal/struct_data_v0.3-16                                                          17996         17630         -2.03%
BenchmarkUnmarshal/string_data_v0.3-16                                                          17431         17137         -1.69%
BenchmarkUnmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v0.3-16     19363         18604         -3.92%
BenchmarkUnmarshal/base64_json_encoded_data_v1.0-16                                             12238         11992         -2.01%
BenchmarkUnmarshal/nil_data_v1.0-16 …
```
> Make tokenQueue a plain slice

- v2/event/event_unmarshal.go
As per title. If cached, the bytes are readily available to be mucked with. No need to reparse necessarily. This spares a full copy for instance.
```
name                                                                                old time/op    new time/op    delta
Unmarshal/data,_attributes_and_extensions_and_specversion_with_struct_data_v1.0-16    16.7µs ± 1%    16.5µs ± 1%  -1.57%  (p=0.008 n=5+5)
Unmarshal/base64_json_encoded_data_v1.0-16                                            11.2µs ± 1%    11.3µs ± 0%  +0.51%  (p=0.032 n=5+5)
Unmarshal/nil_data_v0.3-16                                                            14.7µs ± 1%    14.7µs ± 1%    ~     (p=0.841 n=5+5)
Unmarshal/struct_data_v1.0-16                                                         16.1µs ± 1%    16.1µs ± 1% …
```
> Handle cached byte array directly rather than reparsing

- v2/event/event_unmarshal.go
This is not a performance enhancement. Results are precisely equal. It is however an enhancement in readability and explicitness imo, which is why I send it anyway.
> Completely remove tokenQueue

- samples/kafka/message-handle-non-cloudevents/main.go
- samples/kafka/sender-receiver/main.go
- samples/kafka/sender/main.go
Minor changes, so following the contributing guide, No issue had been opened for this PR.
It concerns kafka samples, it's not the right error that is logged in case of failure
Signed-off-by: Matthieu Bernardin <matt.bernardin@gmail.com>
> Minor fix of kafka samples

- v2/protocol/http/headers.go
- v2/protocol/http/headers_test.go
- v2/protocol/http/protocol.go
Signed-off-by: runzexia <root@junwuhui.cn>
ref https://github.com/knative-sandbox/eventing-github/issues/86
> support custom header from ctx

- v2/event/event_unmarshal_test.go
The #603 is already properly implemented, this PR just adds a test for it
> Added a test for null json attributes

- v2/event/event_unmarshal.go
> do not assume content type is media type

- README.md
- hack/tag-release.sh
> update docs and release script for post release 2.4.0

- .github/workflows/conformance.yaml
- .github/workflows/go-build.yaml
- .github/workflows/go-format.yaml
- .github/workflows/go-unit-test.yaml
- .github/workflows/inclusive.yaml
- .github/workflows/integration.yaml
- README.md
- RELEASING.md
- docs/event_data_structure.md
- docs/index.md
- docs/protocol_implementations.md
- maintainer_guidelines.md
- pr_guidelines.md
> migrate master to main branch name

- docs/index.md
Change marshal to unmarshal on the corresponding section
> Fix error on docs page index

- v2/alias.go
change cloudevents.HTTPOption and cloudevents.HTTPOption from type redefine to type alias
> change options from type redefine to type alias

- OWNERS
Signed-off-by: Alexander Tkachev <sasha64sasha@gmail.com>
> VOTE: add sasha-tkachev to owners

- README.md
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
> Using a more recent version on the README instructions to fetch the dependency

- sql/v2/parser/expression_visitor.go
- sql/v2/utils/casting.go
See: #820
Closes: #820
Signed-off-by: Doug Davis <dug@microsoft.com>
> Avoid int parsing overflow issues

- sql/v2/go.mod
- sql/v2/go.sum
Using newer 1.x version of sigs yaml
> Bump to newer yaml lib versions

- OWNERS
ping @lionelvillardand @markpeek 
The vote will last 1 week, or until Lionel and Mark have voted (whichever comes first)
> vote to add embano1 as a maintainer

- docs/protocol_implementations.md
Refer: https://github.com/cloudevents/sdk-go/issues/901
> append mqtt to the protocol binding doc 

- observability/opencensus/v2/client/client_test.go
- protocol/amqp/v2/write_message.go
- protocol/ws/v2/client_protocol.go
- samples/http/requester-with-custom-client/main.go
- sql/v2/test/tck_test.go
- test/benchmark/e2e/http/http_mock.go
- test/integration/http/tap_handler.go
- v2/binding/test/mock_binary_message.go
- v2/binding/test/mock_structured_message.go
- v2/binding/utils/structured_message_test.go
- v2/client/client_test.go
- v2/protocol/http/message_test.go
- v2/protocol/http/protocol_retry.go
- v2/protocol/http/utility_test.go
- v2/protocol/http/write_request.go
resolve: https://github.com/cloudevents/sdk-go/issues/921
> remove the usage of deprecated `io/ioutil` package

- docs/concepts.md
Ref: https://cloudevents.github.io/sdk-go/concepts.html
> correct the document links

- MAINTAINERS.md
- OWNERS
- README.md
See: https://github.com/cloudevents/spec/pull/1226
> Governance docs per CE PR 1226

- test/integration/mqtt_paho/mqtt_test.go
- test/integration/mqtt_paho_binding/mqtt_test.go
- v2/client/test/test.go
- v2/protocol/test/test.go
This PR tries to make sure that Receivers are started before Senders since (I think) for some protocols we'll lose messages if the Receiver starts after the Sender sends an Event. And in those cases it'll result in a timeout in the tests as it waits forever.
This will also create two separate clients in `SendReceive` since not all protocols like using the same client for sending and receiving messages concurrently.
> Make sure reciever starts before the sender

- test/integration/mqtt_paho/mqtt_test.go
- v2/protocol/test/test.go
Minor clean-up following https://github.com/cloudevents/sdk-go/pull/977
> Make a few comments a bit clearer

- protocol/amqp/v2/message.go
- protocol/amqp/v2/message_test.go
Support multidimensional `data` field in AMQP implementation when converting an AMQP message to a CloudEvent. Writing to AMQP message from CloudEvent remains unchanged because the first slice of `[][]byte` is used to populate the data.
Ref: https://github.com/cloudevents/spec/issues/1275
> fix: support multiple amqp data fields

- .github/workflows/conformance.yaml
- .github/workflows/go-build.yaml
- .github/workflows/go-format.yaml
- .github/workflows/go-lint.yaml
- .github/workflows/go-unit-test.yaml
- .github/workflows/inclusive.yaml
- .github/workflows/integration.yaml
- .github/workflows/observability.yaml
- .github/workflows/release.yaml
Fixed the pinned dependencies which is reported by the [scorecard.](https://scorecard.dev/viewer/?uri=github.com/cloudevents/sdk-go)
Part of #1087
> Fixed the pinned dependencies
